### ISSUE TITLE
Foreingn key contraint with MySQL

### ISSUE THREAD

**Issue by Lucstar** [PiranhaCMS/Piranha#356]
I got this contraint error when saving the default site edit page.

I got a screenshot on the error, it displayed only 1 sec. [http://www.gosso.se/piranhacms/mysqlcontraint.gif](http://www.gosso.se/piranhacms/mysqlcontraint.gif)

What have i done? i uploaded the code first solution on the Binero web hotel. Installed the MySQL database. Logged in, deleted the standard templates and pages/posts. Did make a new startpage. Saved ok. 

Any idea for a work around?

**Comment by tidyui** [comment]
As this is due to the manual database management I'll move it to the next version as it will be replaced with Entity Framework.

**Comment by tidyui** [comment]
I'm closing this issue as MySql support will be dropped until future transition to Entity Framework.
