### ISSUE TITLE
How to describe the stored procedure MSSQL and call it a CMS?

### ISSUE THREAD

**Issue by DFofanov** [PiranhaCMS/Piranha#363]
Good afternoon, misters.

I can't understand as to issue store procedure and to cause it from CMS.

I write as to documentation:
[Function(Name = "usp_SelectCustomer", IsComposable = false)]
public ISingleResult<clsCustomerEntity> getCustomerAll()
{
    IExecuteResult objResult = 
      this.ExecuteMethodCall(this,(MethodInfo)(MethodInfo.GetCurrentMethod()));

    ISingleResult<clsCustomerEntity> objresults = 
        (ISingleResult<clsCustomerEntity>) objResult.ReturnValue;
    return objresults;
}

What's the problem?

**Comment by tidyui** [comment]
Any more info on this question or can I close the issue?
