### ISSUE TITLE
Object reference not set to an instance of an object - @UI.Head()

### ISSUE THREAD

**Issue by mistvan** [PiranhaCMS/Piranha#364]
Hi,

I have added newest Piranha to existing mvc 5 application.
Layout.cshtml was overwritten by instalation and when my webapp is loading I am experiencing this error:
```
[NullReferenceException: Object reference not set to an instance of an object.]
   Piranha.Web.UIHelper.Head() in c:\Proj\GitHub\Piranha-2.2\Piranha\Web\UIHelper.cs:118
   Piranha.Mvc.UI.Head() in c:\Proj\GitHub\Piranha-2.2\Piranha.Mvc\UI.cs:21
   ASP._Page_Views_Shared__Layout_cshtml.Execute() in d:\IT\PROJECTS\gitrepo\majakweb\aspnet\Majak.Web.Site\Views\Shared\_Layout.cshtml:8
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +271
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +122
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +145
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer) +41
```
My RouteConfig.cs has these routes:

```            
routes.MapRoute(
  name: "ProfileView",
  url: "profile/{username}",
  defaults: new { controller = "Profile", action = "Index", username = UrlParameter.Optional });

routes.MapRoute(
  name: "Default",
  url: "{controller}/{action}/{id}",
  defaults: new { controller = "Home", action = "Index", id = UrlParameter.Optional },
  namespaces: new[] { "Majak.Web.Site.Controllers"  }).DataTokens["UseNamespaceFallback"] = false;

routes.LowercaseUrls = true;
routes.AppendTrailingSlash = false;
```
My Views/Shared/Layout.cshtml looks like:
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>@Page.Title</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

        @UI.Head()

        <link type="text/css" rel="stylesheet" href="~/content/css/style.css" />

        @RenderSection("head", required: false)
    </head>
    <body>
        <header role="banner">
            <div class="wrapper">
                <a class="site-title" href="~/">@Site.SiteTitle</a>
                <p class="site-desc">@Site.SiteDescription</p>
                <navigation role="main-navigation">
                    @UI.Menu(StopLevel: 1)
                </navigation>
            </div>
        </header>
        <div class="wrapper">
            @RenderBody()
        </div>
    </body>
    @RenderSection("script", required: false)
</html>
```

Can somebody help me please?

Many thanks,
.miro

**Comment by tidyui** [comment]
Hi there! If you check out the docs for creating a new installation at:

http://piranhacms.org/docs/introduction/getting-started

you can see that the preferred approach for adding Piranha CMS to an existing application is to use the `PiranhaCMS.Mvc` package and not the full template package `PiranhaCMSMvc` which includes views, assets & controllers.

The Layout-file you got from the nuget package assumes that the current page has been loaded from the CMS, and the `@UI.Head` method tries to retrieve the current page/post being executed. If you run a custom route from your existing application these values aren't set which is probably causing the exception.

If you want controllers that are completely separated from Piranha CMS, try remove all references to `@UI` from the Layout-page and add sections for **Head** & **Menu** and so on. You can then in you CMS-views add calls to `@UI.Menu` & `@UI.Head` in these sections and use the same Layout as the rest of your application.

**Comment by mistvan** [comment]
Hi mate, 

I really appreciate your quick reply!

Current status is that webpage (http://localhost:52345) was loaded fine as usual, but I am not promted to install cms or access manager view.

Do I need access some specific url please?

**Comment by mistvan** [comment]
I have more investigated and when I have tried to add `PiranhaCmsMvc` to new asp.net web site I was promted with `manager/welcome/install` route.

This route is not working for my existing webapplication. I have existing HomeController and maybe therefore http://localhost:52345 url is routed to HomeController. Can this be problem?
Next In what controller it should be routed after installing Piranha to  show `/manager/welcome/install` page please?

**Comment by mistvan** [comment]
And is it possible to add Piranha to Visual Studio as project and add it as reference to my existing mvc app to be able to debug it please?

**Comment by mistvan** [comment]
First issue sorted out successfully :)  I have added `Piranha` and `Piranha.Mvc` as projects to Visual studio. 

![image](https://cloud.githubusercontent.com/assets/814958/5679611/44a44812-9802-11e4-8fc5-62a9b0602e29.png)

Then I have added them as reference to my existing project. 

![image](https://cloud.githubusercontent.com/assets/814958/5679613/53a62f92-9802-11e4-8b04-fa63c37099d3.png)



1.Issue
--
Locally I am redirected to /manager page but this error occurs:
![image](https://cloud.githubusercontent.com/assets/814958/5679724/ccd650e4-9803-11e4-922a-7ca6d02c4cdc.png)


2.Issue
--
Then I have deployed my app to test domain and no redirection to Piranha install page occurs.

 When I have manually entered `/manager/welcome/install` it is luckily working. I have created database:
![image](https://cloud.githubusercontent.com/assets/814958/5679567/a4aa1cc4-9801-11e4-89c2-23e15c0331a3.png)
But then this error has occured:

http://test.spolocenstvomajak.sk/manager/page

`Introducing FOREIGN KEY constraint 'FK_dbo.category_dbo.sysuser_category_updated_by' on table 'category' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint. See previous errors.

Piranha.DataContext..ctor() in c:\Users\IEUser\Documents\Piranha\Piranha\DataContext.cs:59
   Piranha.WebPages.WebPiranha.RegisterDefaultHostNames() in c:\Users\IEUser\Documents\Piranha\Piranha\WebPages\WebPiranha.cs:191
`

3.issue
--
And maybe because of Piranha loaded as referenced project some resources are missing at login page:

![image](https://cloud.githubusercontent.com/assets/814958/5679578/c879629a-9801-11e4-91d4-3c53a1be136d.png)

--
I have migration folder with many db migrations and so on. So I am still trying to add Piranha to my existing app and not to create new mvc project.

Any help would be great!

Many thanks

**Comment by mistvan** [comment]
And latest I am experiencing this kind of issue instead of Introducing FOREIGN KEY constraint 'FK_dbo.category_dbo.sysuser_category_updated_by' :
![image](https://cloud.githubusercontent.com/assets/814958/5680866/047a0900-9813-11e4-91ff-633e3284c256.png)

Is it possible to use this https://github.com/tidyui/Blank and copy there all my controllers/migrations/ etc. please? Will it work?

**Comment by tidyui** [comment]
Yes, download the Blank repo and compare what differs. I created it just for these kind of problems!

Regards

**Comment by tidyui** [comment]
And the database errors are because the DbContext are accidentelly trying to create the database (which it shouldn't). The database should be created by the installation process which you don't seem to get!

**Comment by mistvan** [comment]
Yes, I think the same. I have used Blank project and I was promted by install window. I have entered details and was successfully redirected to `/manager/page` but again this error has occured:
Introducing FOREIGN KEY constraint 'FK_dbo.category_dbo.sysuser_category_updated_by' on table 'category' may cause cycles or multiple cascade paths. Specify ON DELETE NO ACTION or ON UPDATE NO ACTION, or modify other FOREIGN KEY constraints.
Could not create constraint. See previous errors.

I am just wondering why there is problem to create foreign key on category table.

**Comment by tidyui** [comment]
Did you really change the connection string in the web.config and renamed it piranha? The error you're getting is because Entity Framework is trying to create the database instead of the embedded create-scripts. If you look at the create-script that is suppose to execute you can see that **category** has no cascade delete for the sysuser foreign key (as opposed to what your error message says).

https://github.com/PiranhaCMS/Piranha/blob/2.2.4/Piranha/Data/Scripts/Create.sql#L189

If you check your database, have the tables really been created? Also, what database are you using?

**Comment by mistvan** [comment]
Yes, I have created this connection String:
```
<add name="piranha" connectionString="data source=localhost;initial catalog=majaksk_piranhadb;user id=majaksk_test;password=k1a2j3a4m5;multipleactiveresultsets=true;" providerName="System.Data.SqlClient" />
```

I am using arvixe hosting and SQL Server 2012 db.

After install window I was redirected to login page. So database was created as it is here:
![image](https://cloud.githubusercontent.com/assets/814958/5700619/1e5ec0d8-9a41-11e4-901b-93f686e73a9d.png)

If you want you can use login mistvan, pass asdfasdf at http://test2.spolocenstvomajak.sk/manager.
For `/manager/page there is now
 ```
[NullReferenceException: Object reference not set to an instance of an object.]
   Piranha.Areas.Manager.Controllers.PageController.Index(String id) +33`
```
For `/manager/post` still `foreign key` error.

**Comment by tidyui** [comment]
Well that explains it. The current Entity Framework assumes that the tables are in the dbo-schema which it doesn't seem to be in your case. Take a look at this pull request:

https://github.com/PiranhaCMS/Piranha/pull/275

Even though @rattrick1 didn't come back with a pull request, maybe you can ask him for advice on the matter.

Best regards!

Håkan

**Comment by mistvan** [comment]
Great, mentioned pull request helped me. Finally it is working for me:
http://test2.spolocenstvomajak.sk/

I really appreciate your help Hakan! This looks like really great project ;) Thanks!

**Comment by arbh89** [comment]
Hi @mistvan, how did you get it to work under other schema, i have been trying but without success, i first create database accessing to manager/install and then move all tables from dbo to new schema also setting entitySchema value to my schema but i still getting same errors that you mentioned erlier.

Thanks in advance.

**Comment by mistvan** [comment]
Hi @arbh89, this was long time ago. I no longer use piranhacms. Hard to find sources for what I mentioned, I am sorry.

**Comment by arbh89** [comment]
I solved this way, first i create a schema called CMS then i moved all tables from dbo to CMS schema, the next step was to create a sql user and give default schema CMS, the connection string is using the new created user and also added <entitySchema value="CMS" /> and is working like a charm.

I am letting this comment just for documentation in case somebody else is facing the same problem.
