### ISSUE TITLE
Login redirect - bug?

### ISSUE THREAD

**Issue by Marknumskull** [PiranhaCMS/Piranha#367]
Hi,

I've just installed Piranha for the first time in a brand new MVC application. I've got the db etc setup as well as the admin account, however, on login i always get redirected to the login screen with no messages and am unable to navigate to the rest of the admin areas.

Any ideas what i've done wrong?

**Comment by DashSplendar** [comment]
I am running into this same issue. I have PiranhaCMS.Mvc 2.2.4 installed in a new MVC project. I have followed the getting started guide, and created the admin account and databases. When trying to log in to the manager interface (localhost:xxxxx/manager), it just redirects me back to the log in page. If I try a username or password different to the admin account, it alerts that the username/password is not found, which makes me think that the authentication is set correctly.

**Comment by tidyui** [comment]
That's weird, as nothing has really changed with the authentication in years :) It almost feels like forms authentication isn't enabled in the **web.config** so the authentication ticket isn't set correctly. Can you confirm that your web.config contains the necessary settings for forms authentication?

You can take a look at the blank MVC repo I set up to show what the end result of a new project should look like (it might not be completely updated to the latest version though). You can find the repo here:

https://github.com/tidyui/blank

Regards

**Comment by Marknumskull** [comment]
I figured it out when I looked again last night - my mistake for not following the getting started correctly. Rather than creating an 'Empty' project with mvc references I created an MVC project with references.

Creating an MVC project must add settings which mess with Piranhas authentication resulting in an endless loop trying to gain access.

**Comment by tidyui** [comment]
Great! Glad it worked out!

**Comment by raviprajapat** [comment]
@tidyui 
I install the Piranha core package
Install-Package PiranhaCMS.Core
With blank MVC project it work with login as admin.
With MVC default project it did not seems to work with login, it redirect back to login page again.
Could you please help me to resolve?
Here is my example repository
https://github.com/raviprajapat/piranaCMS-Example

Thanks,
Ravi

**Comment by eflatz** [comment]
I had the same issue while trying to login via localhost:5000 but when I switched to https://localhost:5001, login and redirection works.
