### ISSUE TITLE
/res.ashx path not working

### ISSUE THREAD

**Issue by mistvan** [PiranhaCMS/Piranha#372]
Hi,

I am experiencing resources error that they are not loading correctly.
I have installed `Piranha` and `Piranha.Mvc` to my existing project

http://test.spolocenstvomajak.sk/manager

```
http://test.spolocenstvomajak.sk/Error/NotFound?aspxerrorpath=/res.ashx/areas/manager/content/css/style.min.css
```

I am guessing that some handler needed for Piranha is not registered correctly or some handler from my application takes precedence before Piranha one, but don't know exactly.

Any help would be appreciate,
thanks

**Comment by tidyui** [comment]
Well I'm just getting an error message that owin can't be found (which isn't used by Piranha) so it's hard to give any feedback.

**Comment by mistvan** [comment]
I have solved this issue. 
I needed to have in Web.config correct culture in globalisation element instead of culture="auto":
```
<globalization culture="en-GB" uiCulture="en-GB" enableClientBasedCulture="true" />
```

So manager is working fine for me.
http://test.spolocenstvomajak.sk/manager

Next I need to resolve another situation.
When I have log into manager and then when tried to access my existing application login page I am getting error:
http://test.spolocenstvomajak.sk/GenericErrorPage.htm?aspxerrorpath=/Account/Login

Can I somehow be logged on both enviroments together please?

Thanks,

My web.config is here
https://www.dropbox.com/s/u7ucuip9505u7ht/web.config?dl=0

**Comment by mistvan** [comment]
Sorry for so many questions, will try to sort this out.
