### ISSUE TITLE
Access right don't work!

### ISSUE THREAD

**Issue by riverstore** [PiranhaCMS/Piranha#375]
Hi! I have problem with access right. 
I added a new permission called "ADMIN_CAP_NHAT_DANH_MUC".

I added a new controller in Areas\Manger in TemplateSite.Mvc project, my controller like this

        [Access(Function = "ADMIN_CAP_NHAT_DANH_MUC")]
        public ActionResult Index()
        {
            var ezlib_dm_BoMon = db.ezlib_dm_BoMon.Include(e => e.sysuser);
            return View(ezlib_dm_BoMon.ToList());
        }

but anonymous users can visit it. I also change to [Access(Function = "ADMIN")] and the anonymous user still can visit the page. Did I make something wrong? Please help me. Thanks a lot.

**Comment by tidyui** [comment]
Hi there! The authentication checks are performed in the base class `Piranha.Areas.Manager.Controllers.ManagerController`. Are your sure your controller inherits from this and not from the standard MVC controller?

https://github.com/PiranhaCMS/Piranha/blob/2.2.4/Piranha/Areas/Manager/Controllers/ManagerController.cs

Regards

Håkan

**Comment by riverstore** [comment]
Thanks a lot! It work fine now. Is there anyway to return to the requested url after logged on?

**Comment by tidyui** [comment]
No, not at the moment. But it would be an easy fix to check a query-parameter for a return url.

https://github.com/PiranhaCMS/Piranha/blob/2.2.5/Core/Piranha/Areas/Manager/Controllers/AccountController.cs#L82

Send a pull request to **2.2.5** and I'll include it in the next release!

Regards

**Comment by tidyui** [comment]
Short update to this. The branch **2.2.5** has been removed and moved into **master** which should be the development branch
