### ISSUE TITLE
Search box in images and documents does not work (/manager/content)

### ISSUE THREAD

**Issue by WouterLeenders** [PiranhaCMS/Piranha#377]
One option is maybe to remove or disable it, if is difficult to implement.

**Comment by tidyui** [comment]
It seems this feature has just been forgotten. However, there's a current issue on converting the media library to loading the tree partially to make it faster (#90) and this would also mean that the search function would have to be implemented somewhat different.

I'll look into it, at the least I'll remove the search field if it's not implemented in the next release to avoid confusion.

**Comment by Twinvision** [comment]
Ok, thx for the info!
