### ISSUE TITLE
Feature Request: Dynamic variables accessible in Razor views

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/Piranha#379]
It would be nice to have some dynamic variables accessible in Razor views.

For instance, I have a layout for a client that has a link to FB, Twitter, etc. It would be nice if they could manage those links while still being part of the layout.

This would also be handy for templates that get used across several sites for things like an About Us section in the footer.

**Comment by tidyui** [comment]
Hi there! Can you elaborate a bit. If go to `Settings > Sites` in the manager interface you can define global regions for your site which you can use across pages or in the layout page of your site. Maybe there's some problem with retrieving the values or did you have something else in mind?

Regards

Håkan

**Comment by Eonasdan** [comment]
ok take [this template](http://wrapbootstrap.com/preview/WB08808B5) for example.

It would be nice to be able to define somewhere in the admin portal (not superadmin) that could be plain text for the phone and email or an image like the logo here:

![image](https://cloud.githubusercontent.com/assets/1006516/5810677/4ad5762a-a018-11e4-89e3-f3dbbeca9b75.png)

or a block of text like this:

![image](https://cloud.githubusercontent.com/assets/1006516/5810681/57e37d94-a018-11e4-9e93-44516cd20cd6.png)

Maybe the site wide regions can do this. How/where does the user edit these regions and how do I access them?

**Comment by tidyui** [comment]
Sorry for not responding, I missed your comment. The site template is edited under `Settings > Sites`, after that you can edit the info by clicking on "Edit Site" on `Content > Pages`.

Regards

**Comment by Eonasdan** [comment]
Ah! Yes. I think this is what I'm looking for. Let's say that I add a new region under `Settings > Sites` that's a simple text and I call the region `Phone`

Now when I do Edit Site on `Content > Pages`, I have a `Title` and `Body` field.

So how do I access those things from the `Layout.cshtml` file?

What about the other content types?

![image](https://cloud.githubusercontent.com/assets/1006516/6051727/99626352-ac98-11e4-93e1-a88d8e4036d1.png)

Feel free to link to the docs if it answers this, as I seem to have missed this there.

**Comment by tidyui** [comment]
Sorry for the late reply. You can quickly get the model by calling the following method:

    Piranha.Models.PageModel.GetBySite(Guid siteId)

And you can get the current site id by calling:

    Piranha.Config.SiteTreeId

Regards
