### ISSUE TITLE
Ashx route not working - Piranha CMS - Failed to load resource

### ISSUE THREAD

**Issue by muhammetsahin** [PiranhaCMS/Piranha#381]
I've got this error :

resource: the server responded with a status of 404 (Not Found)
http://localhost:57352/res.ashx/areas/manager/content/img/ico-edit-24.png Failed to load resource: the server responded with a status of 404 (Not Found)

I found this but i didnt work

http://stackoverflow.com/questions/21177415/ashx-route-not-working-piranha-cms-failed-to-load-resource

I'm using verison 2.2.4.1
.net framework version 4.5.2

How can i solve ?

Thank you.

**Comment by tidyui** [comment]
Hi! How are you using Piranha CMS. Did you set it up using one of the template projects from NuGet, are you adding into an existing application or are you running from source code (and if so, what branch are you using)?

Regards

Håkan

**Comment by muhammetsahin** [comment]
I'm using  piranha.template  from nuget.

**Comment by tidyui** [comment]
PiranhaCMS or PiranhaCMSMvc ?

**Comment by tidyui** [comment]
Did you get your setup to work with the resources?

**Comment by cmeigs** [comment]
I'm having a similar issue here using PiranhaCMSMvc v2.2.3 (via NuGet). Is there a work around? Thanks

**Comment by tidyui** [comment]
I've never been able to reproduce this issue, so the only way for me to help would be if you could share the source code for your project with me!

**Comment by cmeigs** [comment]
I seemed to have found a solution. My issue was with extending the TinyMCE WYSIWYG text editor. I put the TinyMCE.cshtml file in the /Areas/Manager/Views/Shared/Partial/ directory found here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml

The first line consisted of:
﻿<script type="text/javascript" src="~/res.ashx/areas/manager/content/js/ext/tiny_mce/tinymce.min.js"></script>
which included the reference to handler: res.ashx 

I removed the reference to the handler and it seemed to have fixed things.
<script type="text/javascript" src="~/areas/manager/content/js/ext/tiny_mce/tinymce.min.js"></script>

Is there a reason you reference the handler res.ashx in there?

**Comment by tidyui** [comment]
Yes, res.ashx handles all requests to all of the embedded resources for the manager, like stylesheets, images & javascripts. The TinyMCE editor is embedded as well, that's why the default URL points to this URL. But if I'm understanding you correctly, all other embedded resources are served correctly apart from the TinyMCE editor? This makes it even more weird :)
