### ISSUE TITLE
Index needed in Custom Controller

### ISSUE THREAD

**Issue by glerler** [PiranhaCMS/Piranha#383]
Having created custom controllers before I didn't think I would have problems, but......   After creating the controller and views I couldn't get it to work to save my life.    Kept getting a 404.  ???   Turns out I needed  to have an "Index" actionresult in the controller!!!  Didn't have a  need for the 'index' view so I didn't write one!!  Worked correctly afterwards.  Is this by design!!!  Thks for the work!!  Glenn

**Comment by tidyui** [comment]
If you use a custom controller as the route in a page **OR** post type, this is the route that will get executed. If the Index Action is called should just be a matter of how the RouteConfig is set up in your application.

Regards

**Comment by tidyui** [comment]
Did you get it working properly, can I close the issue?

**Comment by glerler** [comment]
Really wasn’t issue, so yes you can close it.  I meant for it to be under general. Sorry.
It works fine as long as I have that index page in the controller.
Been backed up with projects so I have not checked the routes.
I will drop you a note about things.
One question how do I access the UserId for the Admin user currently logged in for that session.
I have a field that logs which user initiated changes and I just save the UserId which looks like it is a GUID.
Thx for your assistance!!
G

Glenn L Erler
Erler Technology Associates
Site Development – Database Solutions – Network Support
glenn@erlertech.com<mailto:glenn@erlertech.com>
480-200-6000

The document(s) and/or file(s) attached to, and the contents of this email is intended only for the individual or entity to which it is addressed, and may contain information that is privileged, confidential, and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by telephone and email and delete this and any copies permanently from your system.

**Comment by tidyui** [comment]
Great. You can find the id of the logged in admin user in `HttpContext.Current.User.Identity.Name` or in `User.Identity.Name` if you're in the scope of a controller.

**Comment by glerler** [comment]
Is there a way to add menu  heading  item to a website without it being a link????
I would like it to be an item that produces a submenu with the  links below.
Add a page creates the site heading but it is a link.  This causes trouble when you want to push the site into a mobile device  and the menu item clicks thru
G



Glenn L Erler
Erler Technology Associates
Site Development – Database Solutions – Network Support
glenn@erlertech.com<mailto:glenn@erlertech.com>
480-200-6000

The document(s) and/or file(s) attached to, and the contents of this email is intended only for the individual or entity to which it is addressed, and may contain information that is privileged, confidential, and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, or the employee or agent responsible for delivering the message to the intended recipient, you are hereby notified that any dissemination, distribution or copying of this communication is strictly prohibited. If you have received this communication in error, please notify us immediately by telephone and email and delete this and any copies permanently from your system.
