### ISSUE TITLE
Adding a custom dropdownlist in a region

### ISSUE THREAD

**Issue by dirodrigues** [PiranhaCMS/Piranha#386]
Hi Hakan,
I was wondering if you could help me with this. I was trying to add a custom list to a region, the value gets saved properly in the database but when loading the page in the manager it doesn't select the previously selected value. I guess I would have to do something like extend the manager controller. Have you got any better suggestions?
Thank you for your time,
Diogo

**Comment by tidyui** [comment]
I'll see if I can post a snippet somewhere for you to look at. I've made many complex regions in the past with dropdowns and have never had the same issue, so it's probably just some quirk in the implementation!

**Comment by dirodrigues** [comment]
That would be great. Thank you very much!

**Comment by itzGiwa** [comment]
@tidyui Hi there, Can you share a sample code for this, I am trying to create custom dropdown lists in a way where the value of one dynamically render a list in the other dropdown

**Comment by tidyui** [comment]
Hi there @itzGiwa, just to make sure. Is this question intended for the old Piranha CMS (`2.5` and below) or the new version (`4.0` and above), as this is the legacy repository for the old version.

**Comment by itzGiwa** [comment]
@tidyui It the 4.2.0, What i am trying to get at is to have a region(with two fields both Ilist<textFiled>) in my custom page where adding texts to first field will push to next fields. Thanks in advance

**Comment by tidyui** [comment]
Hi there! There's no built in support for this, you'll have to write your own fields that support this kind of cross-references. I'm closing this issue at it is in the wrong repository.
