### ISSUE TITLE
Add Layout to SiteTree

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/Piranha#387]
When working with several site trees it's often desired that they should be rendered in a different way. Even though this can be achieved by adding a property/region to the site it might be better to add a more standarized field for what `Layout` page that should be used. This could then be used in the views like so:

```
@{
  Layout = "~/Views/Shared/" + Site.Layout + ".cshtml";
}
```

Solution proposed by @hades200082 in discussion in issue #109

**Comment by hades200082** [comment]
Could also be used in _ViewStart to offer a more global solution.

**Comment by tidyui** [comment]
Anyway I can't add this to the current milestone as the database creation & updates will be replaced with Entity Framework Migrations. In order to ensure a smooth transition the first release has to produce the exact same database schema as 2.2.4. This feature could be added to the next release when we can start working with Migrations from the existing database.
