### ISSUE TITLE
Page title is not rendered

### ISSUE THREAD

**Issue by hades200082** [PiranhaCMS/Piranha#388]
In my layout I have the following.

```csharp
<title>@Page.Title</title>
```

This renders into HTML as...

```html
<title></title>
```

I do have a "Page Title" set in the page editor in Manager.

`@Page` seems to be an empty dictionary.

**Comment by hades200082** [comment]
It seems that @Page is not available in _Layout.cshtml.

Instead I have to set the Title in the ViewBag within the views themselves and use the ViewBag version in the layout.

**Comment by tidyui** [comment]
Piranha CMS was initially created for ASP.NET Web Pages, and in Web Pages "Page" is the equivalent to "ViewBag". I must have slipped when converting the template to MVC. Strange that no one has reported this before :) I'll fix it in the next release.

Regards
