### ISSUE TITLE
Customize Cache Provider

### ISSUE THREAD

**Issue by nhaberl** [PiranhaCMS/Piranha#389]
As I can see caching is a major thing within your CMS I guess it would be a nice feature to register your prefered cache provider when the app starts.
I guess you are not relying ón memcached or Redis which is the prefered way. In addition it would be also a nice teature to change the serializer for something like JIL (https://github.com/kevin-montrose/Jil), which is much faster than the built in one.

**Comment by tidyui** [comment]
The default caching uses HttpRuntime to cache objects and is implemented here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Cache/WebCacheProvider.cs

There’s also a simple MemCache provider here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Cache/MemCacheProvider.cs

And a community provided Redis provider here:

https://github.com/PiranhaCMS/Piranha.Redis/blob/master/Piranha.Redis/Cache/RedisCacheProvider.cs

The cache provider is configured using web.config, but I see a lot of this configuration moving to runtime setup, more like in the Piranha.vNext project. You can read about the different config settings here:

https://github.com/PiranhaCMS/Piranha/wiki/Configuration

Regards

/Håkan
