### ISSUE TITLE
Adding a page programatically

### ISSUE THREAD

**Issue by TimoWillemsen** [PiranhaCMS/Piranha#390]
I'm trying to create a lot of pages at once using the following code:

    public void AddFaqPage(Guid parent, string permalink)
        {
            var templateId = Guid.Parse("c16b62a7-8055-4c59-80ea-3fb0d29bf26b");
            var siteTreeId = Guid.Parse("c2f87b2b-f585-4696-8a2b-3c9df882701e");
            var siteTree = "DEFAULT_SITE"; 

            var em = EditModel.CreateByTemplateAndPosition(templateId, parent, 0, siteTreeId, siteTree);

            em.Permalink = new Permalink()
            {
                Id = Guid.NewGuid(),
                Type = Permalink.PermalinkType.PAGE,
                NamespaceId = Guid.Parse("8ff4a4b4-9b6c-4176-aaa2-db031d75ac03")
            };
            em.Page.IsNew = true;
            em.SaveAll();
        }

But I get an errormessage:

    NullReferenceException: Object reference not set to an instance of an object.]
    Piranha.Models.Permalink.Generate(String str, PermalinkType type) in c:\Proj\GitHub\Piranha-2.2\Piranha\Entities\Internal\Permalink.cs:174
    Piranha.Models.Manager.PageModels.EditModel.SaveAll(Boolean draft) in c:\Proj\GitHub\Piranha-2.2\Piranha\Models\Manager\PageModels\EditModel.cs:457

Whe I look into the stacktrace, it's not the same as in the source control:

    EditModel.cs:457 is this:
    using (var db = new DataContext()) {

So it does't call a function in Permalink.cs at all..

What am I doing wrong?

**Comment by TimoWillemsen** [comment]
This is a dumb way to do this :(

**Comment by tidyui** [comment]
My guess is that the code automatically tries to generate a permalink from the **page title**. The page title is required in the model validation which you've bypassed. When running the regular expression on the title in `Permalink.Generate` it gets a null pointer exception.
