### ISSUE TITLE
Incorrect Permalink being displayed in manager

### ISSUE THREAD

**Issue by mcblake-xx** [PiranhaCMS/Piranha#391]
Hi, I have the latest Piranha MVC (and dependent) Nuget Packages installed and running in VS 2013 development and published to my local IIS as well as a development server.  In all cases, when I set up an additional site from the "manger", and enter a host name, it does not populate the permalink field with the correct host name when I add or edit a page.  Do I need to modify a setting somewhere?  I can navigate to the actual page once it is published, using the correct host name, but the preview function does not work within manager.

Thanks in advance for any help.

**Comment by tidyui** [comment]
I take a look at it just to verify the bug. If I can reproduce it I'll add a fix for it!

**Comment by mcblake** [comment]
Thanks!

**Comment by tidyui** [comment]
I just realized there's a reason for this. The permalink in the manager is populated from the hostname you are currently accessing. As soon as you create a new site and assign a hostname to it the manager interface will be accessible from that hostname as well. When you log into the manager that site will be the default site when navigating to **Page**. Preview links will also be rendered for the hostname you're accessing. The reason for this is:

* In many cases you'll add multiple hostnames, for dev & production. For example `subsite.local, subsite.publicdomain.com`

If you are to render "correct" preview links for all sites the hostname functionality needs to be aware of which one of the host names to choose for the current environment. Any thoughts?

**Comment by tyronegroves** [comment]
How about when you click preview you get a dialog that ask which host you would like to see. If there is just one just use that host.
