### ISSUE TITLE
Allow anonymous user to enter comments

### ISSUE THREAD

**Issue by erwin-beckers** [PiranhaCMS/Piranha#392]
Piranha CMS seems to support comments on posts
However there is no documentation how to enable them.
Can you provide a example of a view which 
- shows the post
- shows all existing posts
- and a form which allows a reader to enter a new comment ?

thanks

**Comment by tidyui** [comment]
The current comment functionality was created, and released before it was fine-tuned. I've never used it myself for a public facing site, instead I always tend to use Disqus or some other third party service as they have a lot of functionality that's missing. This is the main reason that it's missing from the docs, there was always the inteniton to put some more effort in it before promoting the feature.

With this said the included functionality still works and could easily be extended with more functionality where needed. I'll try to put together an example for you, it's pretty straightforward!

Regards

Håkan

**Comment by Lucstar** [comment]
I'm intressed in this answer too, hoping you 're having time to explain since it's straightforward... 

Regards

**Comment by Lucstar** [comment]
For all interested!
I've built a custom form implementation, and i save the data in the comment api.

**Saving to a page:**

```
            dynamic comments = new List<Piranha.Entities.Comment>();

            using (var db = new Piranha.DataContext())
            {
                var page = db.Pages.Where(p => p.Id == Model.Page.Id).SingleOrDefault();
                comments = page.Comments;
                //create
                page.Comments.Add(new Piranha.Entities.Comment() { Title = "mytitle", Body = body, AuthorEmail = authoremail, AuthorName = authorname });
                db.SaveChanges();
            }
```
