### ISSUE TITLE
Hooks: Need a bit of guidance here

### ISSUE THREAD

**Issue by xxcrystalcat** [PiranhaCMS/Piranha#394]
Hi Hakan,

I'm trying to add styling to a multi level menu - I'm not really sure if I'm on the right track - please advise? I've been looking at this too long and am not able to render anything with the attached code.

![capture](https://cloud.githubusercontent.com/assets/5788740/6766125/576aff8a-d002-11e4-9cc5-b86a6f827a30.PNG)

**Comment by tidyui** [comment]
Hi there! Hooks are static delegates, much like events and should (most of the times) be assigned **once** in the application lifecycle. This means you should always assign your hooks in `Global.asax.cs` or `_AppStart.cshtml` depending on your project. 

Furthermore, the menu hooks are called from within `@UI.Menu` which seems to be missing, so my tip would be:

1. Move all of your hooks to the application startup
2. Replace all of you code above to `@UI.Menu()` so you get something like:

    &lt;div class="inner-nav desktop-nav"&gt;
      &lt;ul class="clearlist"&gt;
        @UI.Menu()
      &lt;/ul&gt;
      ...
    &lt;/div&gt;

Regards

Håkan

**Comment by tidyui** [comment]
Also, if you want to create a totally custom menu, you don't have to use the built in `@UI.Menu` and the hooks at all. Getting the sitemap is just a single call like this:

    var sitemap = Piranha.Models.Sitemap.GetStructure();

You could then render it anyway you like, preferably using DisplayTemplates.

    @{
      var sitemap = Piranha.Models.Sitemap.GetStructure();
    }
    <div class="inner-nav desktop-nav">
      <ul class="menu">
        @foreach (var item in sitemap) {
          Html.Display(item)
        }
      </ul>
    </div>

And then a display template called Sitemap with a markup something like this:

    @model Piranha.Models.Sitemap
    <li>
      <a href="@UI.Permalink(Model.Permalink)">@Model.Title</a>
      @if (Model.Pages.Count > 0) {
        <ul>
          @Html.DisplayFor(m => m.Pages)
        </ul>
      }
    </li>

Please note that the above example is greatly **simplified** and doesn't look at the active node or navigation title. But it is an option anyway :)

Regards

**Comment by xxcrystalcat** [comment]
Thank you so much! That has saved me a lot of time :)

**Comment by tidyui** [comment]
No problem!

**Comment by xxcrystalcat** [comment]
I'm getting this error: 
 CS1928: 'System.Web.WebPages.Html.HtmlHelper' does not contain a definition for 'Display' and the best extension method overload 'System.Web.Mvc.Html.DisplayExtensions.Display(System.Web.Mvc.HtmlHelper, string)' has some invalid arguments 

Apologies if I'm being a bit blonde here

**Comment by xxcrystalcat** [comment]
Apologies, but how do I find the active node?

**Comment by tidyui** [comment]
Hi again! The easiest way is probably to take a look in the source code for the `@UI.Menu` helper located in this file:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Web/UIHelper.cs

On this line for example you can see how active is calculated:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Web/UIHelper.cs#L532

And here is the method `ChildActive` which is used:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Web/UIHelper.cs#L597

Best regards!

Håkan

**Comment by xxcrystalcat** [comment]
Hi Håkan

I need to do a search facility and integrate it into Piranha for my project which has a tight deadline - would you be able to point me in the right direction with this? At the moment it's a bit daunting :)

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by tidyui** [comment]
No problem! Send me a mail (or create a new issue) with more details on **what** and **how** you search is supposed to function. I'll put together some generic code and share it online so you and others can use it!

Regards

Håkan

**Comment by xxcrystalcat** [comment]
Thank you so much!!

Basically if someone wants to search the site for a particular word, phrase or document throughout the site ie: Like a WordPress(cringe, yes I said it lol) search where it allows you to find content within posts, pages, etc.

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by tidyui** [comment]
How will you implement the search in your webpage. Are you implementing a "live-search" function so you want the results to be returned as JSON through a REST api, or are you building a standar full-post search.

Also, what fields should be returned from the search. Given that we're searching on multiple types (pages, post, categories) I'm guessing something should be returned that tells you what the result is. For example:

    results = [
      { "type": "page", "title": "My first page", "desc": "Lorem ipsum", "url": "http://yousite.com/my-first-page" }
    ];

**Comment by xxcrystalcat** [comment]
Yes a rest API with json result is perfect!

I'd like a result to be returned which brings back title, description, permalink, date created, author. For either page, post or category, etc. It will need to be very content driven as the site contains (far too much) information regarding products and services (http://4mvc.net)

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by tidyui** [comment]
I've created a Gist here that you can use as a starting point. It uses **Web Api 2.2** so you'll need to include this package from NuGet if you don't have it already. Remember to add startup code in Global.asax.cs and add the WebApiConfig.cs that you get scaffolded when you create a Web Api project in Visual Studio. The only way to do complex searches fast is to use good old fashioned **Sql** so I hope you're familiar with that :)

https://gist.github.com/tidyui/c11597599415ec6e9c83

Feel free to update the Gist when you've improved it further! Maybe we can add it into a package later on!

Regards

/ Håkan

**Comment by xxcrystalcat** [comment]
Awesome stuff !! Thank you :) I will definitely contribute when I get it right :D

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by tidyui** [comment]
Btw @xxcrystalcat, I would really love if you, as a user, would send me some feedback on Piranha CMS when you get the time. How you use it, strong and weak points, what you spend most of the time on in projects and what could be improved for a smoother and faster workflow!

All of your thoughts are greatly appriciated!

Regards

**Comment by xxcrystalcat** [comment]
Will do so tonight :)

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by xxcrystalcat** [comment]
Ah I see what you meant earlier about webpages now – I can’t install the Piranha.Mvc package, how do I access UI.(Method) without it? Do I need to inherit from Basepage?


Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]

**Comment by tidyui** [comment]
I see! I updated the Gist a bit to use the generic UIHelper that's in the core library instead of the static version in the MVC project. Now it should work for both MVC & WebPages.

Regards

**Comment by xxcrystalcat** [comment]
You are awesome! Thank you!!

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za
________________________________

**Comment by xxcrystalcat** [comment]
I’m getting a 404 – do I need to touch routing in any way?


Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]

**Comment by tidyui** [comment]
After you've installed **Web Api** you need to add the standard startup code for it. This typically involves the following line in `Global.asax.cs`

    GlobalConfiguration.Configure(WebApiConfig.Register);

And then a class called `WebApiConfig` with the `Register` method, usually looks like this:

    using System;
    using System.Web.Http;

    namespace MyNamespace
    {
      /// <summary>
      /// Configures the WebApi routes.
      /// </summary>
      public static class WebApiConfig
      {
        /// <summary>
        /// Registers the WebApi routes.
        /// </summary>
        /// <param name="config">The current HTTP config</param>
        public static void Register(HttpConfiguration config) {
          // Web API routes
          config.MapHttpAttributeRoutes();

          config.Routes.MapHttpRoute(
            name: "DefaultApi",
            routeTemplate: "api/{controller}/{id}",
            defaults: new { id = RouteParameter.Optional }
          );
        }
      }
    }

If everything is configured properly WebApi the `Get` method in `SearchController` will be accessed on:

    GET: /api/search/my-search-keyword

Hope this helps. Note that I didn't try it in a **WebPages**, since I thought you were using **MVC**. But there shouldn't be any problem getting it to run together with WebPages.

Regards

**Comment by xxcrystalcat** [comment]
Worked absolutely perfectly –thank you so much for your assistance, I really appreciate it!

Kind Regards,
Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>
[MCSD]

**Comment by xxcrystalcat** [comment]
Ok awesome, and last question is regarding uploading of documents – I can’t seem to find documentation on that.

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]

**Comment by xxcrystalcat** [comment]
I haven’t gotten to this yet but it is on my todo as soon as this project is out of the way ☺

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]

**Comment by tidyui** [comment]
Hi there @xxcrystalcat I responded earlier, but it seems like the message went missing. On the other hand GitHub has been up and down.

When you say "uploading of documents" do you mean documents that should become visible in the manager or documents controlled by the application?

Regards

Håkan

**Comment by xxcrystalcat** [comment]
Hi Håkan

So I’m going to write a form for those wanting to upload and send their CV to Britehouse, I’d like to keep within Piranha framework as I tend to deviate from frameworks when I’m not sure.

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]

**Comment by tidyui** [comment]
In that case a nice solution would be to create a folder in the media library called "Resumes" or something and then store uploaded files there. This way it will be easy for administrators to find them afterwards.

The easiest way to achieve it is just to take a look at the ContentController in the manager Area and borrow some logic from there.

Just remember to manually login to the database object as it requires a Piranha CMS user to store data.

I can give you some pointers on Monday if you get stuck!!

Regards

**Comment by tidyui** [comment]
Sorry for not getting back to you @xxcrystalcat but how did it go with the document upload?

**Comment by xxcrystalcat** [comment]
Hi Håkan,

Thanks for following up – I unfortunately ran out of time with the upload as the entry was due on Monday – but that’s ok – my entry did win the internal contest but they decided to go with the second winner’s SharePoint solution with my front end (Being a predominantly SharePoint based company).

However – they know what Piranha is now and we will be implementing it across more of our future projects from our custom dev team’s perspective ☺  My colleague is incidentally in anticipation of the new authentication release that you blogged about a while ago.

I’d still like to work on that upload method as it will be very useful in the future so as soon as I grab a spare moment (I have to integrate the front end with SharePoint now (!!)) I will definitely try contribute with the new additions :D Thank you so much for the consistent and fast support – this project was done in under a week with Piranha (very powerful!) – I think the support above all else means that Piranha is so awesome and continues to be :D

Kind Regards,

Christine Ollewagen
+27 (0) 79 884 0630
www.crystalcat.co.za<http://www.crystalcat.co.za/>

[MCSD]
