### ISSUE TITLE
Looking for ApplicationModule.cs and WebPirahna.cs on new install

### ISSUE THREAD

**Issue by WizbangRob** [PiranhaCMS/Piranha#395]
Hi,

I'm following the Getting Started guide on a new website (tried both MVC and Web Pages), but when I try to run for the first time in VS 2013 it's looking for and failing to find WebPiranha.cs and ApplicationModule.cs files in c:\Proj\Github...

The following is the exception that I'm getting:

[FileNotFoundException: Could not load file or assembly 'AutoMapper, Version=3.3.0.0, Culture=neutral, PublicKeyToken=be96cd2c38ef1005' or one of its dependencies. The system cannot find the file specified.]
   Piranha.Application..ctor() in c:\Proj\GitHub\Piranha-2.2\Piranha\Application.cs:152
   Piranha.Application..cctor() in c:\Proj\GitHub\Piranha-2.2\Piranha\Application.cs:25

[TypeInitializationException: The type initializer for 'Piranha.Application' threw an exception.]
   Piranha.WebPages.WebPiranha.BeginRequest(HttpContext context) in c:\Proj\GitHub\Piranha-2.2\Piranha\WebPages\WebPiranha.cs:321
   Piranha.Web.ApplicationModule.<Init>b__0(Object sender, EventArgs e) in c:\Proj\GitHub\Piranha-2.2\Piranha\Web\ApplicationModule.cs:38
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69

I don't understand why it's looking for these source code files. Am I supposed to install them on my local machine? I thought that installing the modules via NuGet was all that I needed to do.

Regards,
Rob

**Comment by tidyui** [comment]
Hi there! The message is just the debugger trying to locate the source files to show you the error. The real error is that AutoMapper is missing.

You need to update PiranhaCMS.Core to version 2.2.4.1 which will resolve the problem.

Regards

**Comment by WizbangRob** [comment]
Thanks for you comment. I'm not sure how to go about updating to 2.4.1. Could you please advise.

**Comment by tidyui** [comment]
To update Piranha.Core to **2.2.4.1** (not 2.4.1), choose "Manage NuGet Packages" by right-clicking on your project. Once the package manager explorer opens click on "Updates" in the left-hand menu. There you will see an update for Piranha.Core.

Regards

**Comment by WizbangRob** [comment]
Thank you. That worked.

**Comment by tidyui** [comment]
Great!
