### ISSUE TITLE
Changinging culture to de doesn't work

### ISSUE THREAD

**Issue by nhaberl** [PiranhaCMS/Piranha#397]
When I set the globalization tag under system.web with de-DE and de it has no affect - the manager interface uis still english. Are tzere any other settings to consier? Couldn't find a lot to this topic in the docs.
I'm using IIS Express 8, if it's from use.

**Comment by tidyui** [comment]
Did you set both Culture & UI Culture?

Regards

Håkan

**Comment by nhaberl** [comment]
Yes ... look here is my setting

<system.web>
      <globalization
           culture="de"
           uiCulture="de-DE"
           ...
           ...
        />
   </system.web>

**Comment by nhaberl** [comment]
Hi, I still have this problem ... have you ever tried it in German ?
Also tried to set the ThreadCulture on BeginRequest - without success.

My value in the root web.config: 
<system.web>
    <globalization uiCulture="de-DE" culture="de-DE" enableClientBasedCulture="false" />
...

Really don't know what to do, maybe you can help a bit :)

Thanks
Norbert

**Comment by tidyui** [comment]
You are right! The resources are actually missing from the NuGet-package! It will be corrected with the 2.2.5 release!

Regards
