### ISSUE TITLE
Getting Parent Page from PageModel

### ISSUE THREAD

**Issue by dirodrigues** [PiranhaCMS/Piranha#398]
Hi (again) Hakan,
Sorry to bother you, but I was wondering what is the best way to get the Parent Page Id from the Piranha.Models.PageModel .

Cheers,
D

**Comment by tidyui** [comment]
Hi there!

The property `Page` is exposed as the interface IPage, but it will in fact **always** be implemented by Piranha.Models.Page. I can add the property `ParentId` to the interface, but until then you can type case the interface to Page to access the parent id.

    var parentId = ((Piranha.Models.Page)model.Page).ParentId;

Regards

Håkan

**Comment by dirodrigues** [comment]
Perfect.
Thank you again.
D
