### ISSUE TITLE
Menu Dilemma

### ISSUE THREAD

**Issue by glerler** [PiranhaCMS/Piranha#403]
I have a multilevel  menu that I display using CSS.  I use bootstrap for mobile responsiveness.  It all works fine except....  When you create the top level page in the manager it make the top menu up as a link.   When the site goes into mobile on  phone and tablet touch screen when the user touches the menu the dropdown  works but since the top is a link it navigates the user away.   Not having the toplevel be a link would solve the issue but i have not come up with a solution.  Am I missing something stupid and easy.  Thx

**Comment by tidyui** [comment]
Hi! Like you say, by default all menu items are rendered as links. There are however hooks available for customizing the menu item rendering that you can take a look at here:

http://piranhacms.org/docs/api-reference/hooks

You should be able to use the hook `Menu.RenderItemLink` and customize it like:

    Hooks.Menu.RenderItemLink += (ui, str, page) {
      // Check if this is the startpage of the site.
      if (page.ParentId == Guid.Empty && page.Seqno == 1) {
        // Render the page title without the link
      } else {
        // Render the page title and a link
      }
    };

Regards

Håkan

**Comment by glerler** [comment]
I have been looking at the Hooks to see if that would work.  The issue I run into is;  
1.The navmenu displays on all pages in the mast.
2. Not all navmenu items have a dropdown menu.
3. So I need to selectively make certain menu items not a link.
If anyone else has an alternative solution, suggestion I would love to hear it.
Thanks for the reply

**Comment by Eonasdan** [comment]
@glerler I use this code to create the menu:

```
@using Piranha.Models
@{
    IEnumerable<Sitemap> sitemap = Sitemap.GetStructure().Where(x => !x.IsHidden && x.IsPublished);
    
    <ul class="nav navbar-nav">
        @foreach (Sitemap page in sitemap)
        {
            if (page.Pages.Count == 0)
            {
                <li class="">
                    <a href="/home/@page.Permalink">@page.Title</a>
                </li>
            }
            else
            {
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">@page.Title <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        @foreach (Sitemap subPage in page.Pages.Where(x => !x.IsHidden && x.IsPublished))
                        {
						<li class="">
							<a href="/home/@subPage.Permalink">@subPage.Title</a>
						</li>
                        }
                    </ul>
                </li>
            }
        }
    </ul>
}
```
