### ISSUE TITLE
Got 404 error on controller in Manager area

### ISSUE THREAD

**Issue by riverstore** [PiranhaCMS/Piranha#412]
Hi! I just download the latest commit, I create a folder called "Controllers" under the Manager folder in the TemplateSite.Mvc project and add new controller, view, on trying to access to the view in the controller I got 404 error. Anyone please help me. Thanks a lot

**Comment by tidyui** [comment]
Hi there!

You need to specify which namespaces to include in the routing for the manager area in your web.config.

    <managerNamespaces value="" />

Here you can add a comma separated list of namespaces. You can read more about the available configuration here:

https://github.com/PiranhaCMS/Piranha/wiki/Configuration

Regards!

**Comment by riverstore** [comment]
Thanks! It's work fine now
