### ISSUE TITLE
Error on submit HTML contents

### ISSUE THREAD

**Issue by riverstore** [PiranhaCMS/Piranha#413]
Hi! First I know that this not relate to Piranha but I googled and found some solutions but it not work for me so I ask here, please help me.

I got error message "A potentially dangerous Request.Form value was detected from the client" on trying to submit HTML contents, I see that you can post HTML when create new post, I read the code but can found the way to solve the problem.

Please help me. Thanks a lot.

**Comment by tidyui** [comment]
Hi there! Usually, adding the ValidateInput(false) attribute to your save action is enough, take a look at the method for saving a post for reference:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Controllers/PostController.cs#L99

Regards

**Comment by riverstore** [comment]
Thanks alot. You saved my life :)
