### ISSUE TITLE
How to get attachment info?

### ISSUE THREAD

**Issue by hungdalat** [PiranhaCMS/Piranha#415]
Hi guys,

My post have many attachments is image.
I want to get all info of attachment, ex: name, desctiption, alt,...

`forech(var post in posts){`
`<h2><@post.Title>`
`forech(var att in post.Attachments){`
`<p>name att: </p>`
`<p>desctiption att:</p>`
`<p>alt att:</p>`
`}`
`}`

Thank you so much.

**Comment by tidyui** [comment]
The `Post` object is just a data entity. The `PostModel` is however the full client model which contains attachments, regions and so on. So if you had a list of PostModels, you could just write.

    @foreach (var model in posts) {
      <h2>@model.Post.Title</h2>
      @foreach (var att in model.Attachments) {
        <p>@att.Name</p>
        <p>@att.Description</p>
        <p>@att.AlternateText</p>
      }
    }

**Comment by hungdalat** [comment]
@tidyui  thank you for reply

but in here my model.Attachments is List<Guid> ???

please view  screenshot:

![debug](http://mbiz.com.vn/images/debug.jpg)

---------------------
@using System.Data.Entity
@{
    var menuDiemTam = new List<Piranha.Entities.Post>();
    using (var db = new Piranha.DataContext())
    {
        menuDiemTam = db.Posts
          .Include(p => p.CreatedBy)
          .Where(p => p.Template.Name == "MenuDiemTam")
          .OrderByDescending(p => p.Published)
          .Take(4).ToList();
    }
}

**Comment by tidyui** [comment]
Yes, you should replace your code to getting the **full** PostModel instead.

    @using Piranha.Entities
    @{
      var menuDiemTam = PostModel
        .Where(p => p.Template.Name == "MenuDiemTam")
        .OrderByDescending(p => p.Published)
        .Take(4).ToList();
    }

Then use the code I provided in the previous reply. Another **even easier** approach is to add a **PostModels** region to your **Page Type** which loads four post models of the selected type. Then you don't have to write the data-access code in your page.

Regards

Håkan

**Comment by hungdalat** [comment]
thank you so much @tidyui LIKE PiranhaCMS :)

**Comment by tidyui** [comment]
Great!
