### ISSUE TITLE
Use my controller as default page

### ISSUE THREAD

**Issue by riverstore** [PiranhaCMS/Piranha#416]
Hi! I use the TemplateSite.Mvc project for my site. I create a new controller called "Index" and want to use it as the homepage.  I tried to edit RouteConfig.cs to

			routes.MapRoute(
				name: "Default",
				url: "{controller}/{action}/{id}",
				defaults: new { controller = "Index", action = "Index", id = UrlParameter.Optional },
                namespaces: new[] { "LacHong.Controllers" }
			).DataTokens["UseNamespaceFallback"] = false ;

but it still open the old default page

Please help me. Thanks alot.

**Comment by riverstore** [comment]
I google and read the core source code but can't found the way to do. 
Please help me. Thanks a lot.

**Comment by tidyui** [comment]
Hi there! Unless you're running in **passive mode** the startpage will always be intercepted by the CMS routing. You can however create a page type without any CMS regions and configure its route to point to any controller/action that you want!

Regards

Håkan

**Comment by riverstore** [comment]
Hi! Thanks a lot for answering my question. Do I just set passiveMode to true then it will work? 

PS: Sorry, my computer can't boot now so I can check before ask you.

**Comment by tidyui** [comment]
However, if you use PassiveMode all routing will be bypassed, is this what you're looking for

**Comment by riverstore** [comment]
Hi! I'm still use the Piranha's manger (with some custom managers from my project). Will it be bypassed?

**Comment by tidyui** [comment]
No, the manager interface will still be active!

Regards

**Comment by riverstore** [comment]
Today my computer can boot, just checked and it work as I need. Thanks a lot!
