### ISSUE TITLE
Error after clean install

### ISSUE THREAD

**Issue by Bengkel** [PiranhaCMS/Piranha#417]
I started a new MVC project and add the Piranha NuGet Package. I was prompted to install the database and was able to log in. After that I received this exception:

![image](https://cloud.githubusercontent.com/assets/6442129/7756187/e6c6973a-fff9-11e4-97e7-6d8d2a901b0c.png)

Can anyone tell me how to fix this?

I use a local MS SQL database.

**Comment by everschoor** [comment]
I installed Piranha via NuGet yesterday, I can only access the installation page (localhost:xxx/manager/install/welcome ) and manager page (localhost:xxx/manager) .
When I open a home or draft page, I receive the error message below:

![image](https://cloud.githubusercontent.com/assets/12549657/7756459/a73a8778-fffb-11e4-9bb5-00bf2e5c6022.png)

**Comment by tidyui** [comment]
I can reproduce the error described by @Bengkel. There seem to by some cache miss when the application is initialized before database install.

To resolve, just restart the application after database install. This is acheived by recompling or just saving the web.config.

Regards

**Comment by tidyui** [comment]
Did you perform the installation @everschoor? If so, try the above solution.

**Comment by Bengkel** [comment]
Restarting did solve the issue.
Thx

**Comment by everschoor** [comment]
Thanks @tidyui for your fast reply.
I'd try to get PiranhaCMSMvc working using VS2015 RC in my previous post, but that resulted in the error message shown above.

However, I was manage to get PiranhaCMSMvc running using VS2013 Pro using the same installation steps as described....

Just to let you know..

Regards

**Comment by tidyui** [comment]
I haven't really tried it out in VS2015 yet @everschoor. When VS2015 is released the big job will be adapting everything to run within the new web context and to compile for cloud as the current implementation is dependent on System.Web and the singleton instances it exposes.

**Comment by tidyui** [comment]
Referenced wrong issue
