### ISSUE TITLE
Implementing a ICacheProvider prevents logging into the manages section

### ISSUE THREAD

**Issue by mike-jewell** [PiranhaCMS/Piranha#418]
I have implemented a Redis implementation of the ICacheProvider.  When using the provider I can no longer get access to the admin section of Piranha CMS.  I have isolated the problem and can submit a fix, as it is relatively straight forward.

What is the process?

**Comment by tidyui** [comment]
Hi there! I can't merge your PR. I you take a look at the PR it involves 250+ commits over 1300 changed files, so I'm guessing you're committing some kind of large merge with your request. Can you isolate the fixes you've made into a separate Pull Request, cause right now I can't even find your modifications in the list :)

Regards

Håkan

**Comment by mike-jewell** [comment]
Hi Håkan, sorry about that, first time using github and a pull request.

I have created another pull request with a branch etc so it has the single file changed.  Hope this is correct ;)

https://github.com/PiranhaCMS/Piranha/pull/420

Cheers

Mike

**Comment by tidyui** [comment]
Great :) I've merged it!
