### ISSUE TITLE
Changing View on existing PostType

### ISSUE THREAD

**Issue by LucGosso** [PiranhaCMS/Piranha#421]
Hi Håkan,
version 2.2.4 "Web Pages" 
How do i change the default route of an specific post type "NewsPost"? 

I want it to be "/news/newstitle" where there is a page on "/news"

Regards.

**Comment by tidyui** [comment]
There's currently no built-in support to change the routing of posts. Furthermore, if a page would be present with the permalink `/news` requests for `/news/newstitle` would be routed to the page to enable routing of different `actions` to the pages.

However, the blogging & archive support in the current version is rather rudimentary so there are thoughts on improving this. If this were implemented it would most likely be:

* Your post type **News** would have the slug `News`
* Requests to `/news` would be routed to the archive page for News.
* Posts of the type **News** would have the permalink `/news/post-slug`.

Regards

**Comment by Lucstar** [comment]
ok, is there a way of hooking up on the save post event? and then change permalink on the post slug? then it would be working I asume.

Best Regards
