### ISSUE TITLE
Modernize templates

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/Piranha#422]
The site templates feel rather outdated. Here are some suggestions to updates:
- Move static files from `/content` to `/assets`
- Use bootstrap as base css framework
- Include some useful page types / templates for getting up and running fast

More suggestions are **much** appreciated!

**Comment by Eonasdan** [comment]
Really really far from done, but here's my crack at bootstrap-ing the admin area

![image](https://cloud.githubusercontent.com/assets/1006516/8121144/71e5ce04-1075-11e5-82a9-a1edd008181a.png)

![image](https://cloud.githubusercontent.com/assets/1006516/8121146/75050f00-1075-11e5-8491-b3e793c391fe.png)

**Comment by Eonasdan** [comment]
and for kicks here it is with the "Slate" theme

![image](https://cloud.githubusercontent.com/assets/1006516/8121186/0ea07b9a-1076-11e5-9876-55ae9f869af7.png)

**Comment by tidyui** [comment]
Nice! However this issue was more about modernizing the start templates for the public site when starting with `piranhacms` or `piranhacmsmvc` packages.

**Comment by Eonasdan** [comment]
I think at some point I realized that you were talking about the starter templates and not the admin area but I figured I might as well go far enough for a demo.

I'd love to see bootstrap be the base for the admin area. Do you want me to continue?

**Comment by Lucstar** [comment]
Hi Håkan and Eonasdan, 

I don't see the point of updating the cms admin ui. It should be secondary. The amount of effort against usability or effect is low. But the more useful to supply start templates for developers, to get up running fast. 

I´ve made one starter template for myself implemented in Bootstrap and PiranhaCMS 2.2.4 .net webpages that you could use. I'm new to GitHub, so i don't know how this contribute works. 

Anyhow here is some websites with this template

* http://www.krusiusalpackor.se/
* http://lindovilla.se.preview.binero.se
* http://www.ostgotamarknader.se/

The notice-areas in top on startpage are a Type of "Post" that i connect with Category "StartPage"

The solution has three pagetypes: Startpage, articlepage and newslistpage
Posttypes: NewsPost and StartPageNoticesPost

Quite simple template! Responsive and menu in lot of levels.

Let me know if you want my solution or how i can contribute. 

Regards Luc

**Comment by Eonasdan** [comment]
@Lucstar one of your sites `http://lindovilla.se.preview.binero.se/` throws a yellow screen of death btw.

As @tidyui pointed out, this issue was actually for the template sites and not the admin area.

I disagree with your point about not changing the admin ui. Both the template sites and the admin area should be changed to use Bootstrap. Mobile first design is the key to site design these days. The admin area would have a lower barrier to customization using Bootstrap and it would be much cheaper

**Comment by tidyui** [comment]
Well I started working on a completely new Admin UI based on Bootstrap for the Piranha.vNext project. This is something that could be used as a start if one would like to update the UI for the existing version. See some screenshots below.

![skarmavbild 2015-06-16 kl 14 44 40](https://cloud.githubusercontent.com/assets/781266/8183177/84fb5706-1436-11e5-96bb-dec87be739ea.png)
![skarmavbild 2015-06-16 kl 14 44 49](https://cloud.githubusercontent.com/assets/781266/8183180/89ff4898-1436-11e5-95ad-453bfdb45128.png)
![skarmavbild 2015-06-16 kl 14 44 58](https://cloud.githubusercontent.com/assets/781266/8183181/8d78ed6c-1436-11e5-964b-614cf19e485b.png)

**Comment by rafcontreras** [comment]
@Eonasdan Do you have a repo for the Bootstrapping of the admin area?

**Comment by Eonasdan** [comment]
@rafcontreras no I'm afraid not sorry. :(

**Comment by cvillard** [comment]
Though this article did not pertain to the Admin Manager area, if I wanted to redo mine installed version, or at least make the login page look like my custom site, how would I go about doing that?
