### ISSUE TITLE
Site Settings

### ISSUE THREAD

**Issue by amergill** [PiranhaCMS/Piranha#424]
Is there a way to extend the site setting entity?  Currently only Name and Description appear to be editable?

i.e add Logo?

manager/sitetree/edit/

**Comment by tidyui** [comment]
Yes! If you go to Settings > Sites in the manager and click on your site you'll see that you can add regions to it just like with any other page type. Save the site and then go back to editing it and you'll see that you can edit the different regions you created.

Regards
