### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by mohrtan** [PiranhaCMS/Piranha#425]
I was investigating using your REST API to get content from Piranha as described in this issue https://github.com/PiranhaCMS/Piranha/issues/233. However, this call:

```
Piranha.WebPages.WebPiranha.InitServices();
```

Is marked as obsolete in the latest version. I'm wondering how you init the REST services in latest and if the calls as documented in https://github.com/PiranhaCMS/Piranha/issues/233 are still valid.

**Comment by mohrtan** [comment]
I was able to find your NUGET legacy package and now have that running. So the REST API is initilazed with the call to:

   Piranha.Legacy.Services.Module.Init();

Now, I'm getting this error when I make a REST call to get a page:

   Could not load type 'Piranha.Web.APIKeyAuthorization' from assembly 'Piranha'.

This is the rest call I'm making:

   /rest/page/get/resourcefulness?apikey=<my generated api key>

**Comment by mohrtan** [comment]
More progress to report this morning, however I'm still not over the finish line. I found the new location of the `APIKeyAuthorization` class and updated `web.config`, but now I get a "Request Error" page with this message:

    The server encountered an error processing the request. See server logs for more details.

There are no log files in `App_Data\Logs`.

**Comment by tidyui** [comment]
Hi there. You can always turn of the API key auth just by removing it from the web.confg

**Comment by phusuke** [comment]
So does the latest version have a REST API? Not sure how to enable it/use it.

**Comment by phusuke** [comment]
@tidyui Removing the auth works, but how can I get it to work with the auth? 
Also can you give me a resource/docs where I can see how to retrieve the posts myself and maybe build out my own API layer? Thanks! and great job with the CMS btw

**Comment by cnascimento** [comment]
Taking advantage of the question. It is possible to implement per-user authentication and password in APIKeyAuthorization class?

**Comment by Rathje** [comment]
Hi mohrtan and tidyui,

First of all I'm new to piranha, but extremely happy with it as one of the few mvc cms systems out there...

Did you guys get any further with re-activating the legacy apikey functionality?
Or is it better to build your own authorization maybe using the still active apikey properties?

My goal is to have users (or apps) registered in piranha and then by choice give them access with apikeys either without logging in or through my custom api...

Best regards
Lars, Denmark

**Comment by mohrtan** [comment]
Our implementation led us in a different path than using the built-in API, so I cannot offer you any insights. I can tell you that we have had great success working with Piranha in general.

**Comment by Rathje** [comment]
OK thanks mohrtan anyway for a rapid response...
Lars
