### ISSUE TITLE
Form Post

### ISSUE THREAD

**Issue by Bengkel** [PiranhaCMS/Piranha#426]
How do i post a custom form from a view?

@using (Html.BeginForm("SendMail", "Contact", FormMethod.Post)) 

now throws an error 

[NullReferenceException: Object reference not set to an instance of an object.]
   Piranha.Models.Page.GetByPermalink(Guid siteTreeId, String permalink, Boolean draft) +111

**Comment by tidyui** [comment]
If you post to a controller that inherits from `SinglePageController` or `SinglePostController` without using its permalink instead of controller name the underlying logic will fail when the base class tries to resolve the current CMS page.

This causes the error you have included.
