### ISSUE TITLE
Invalid object name 'sysparam'.

### ISSUE THREAD

**Issue by NickOhara** [PiranhaCMS/Piranha#429]
Hi,

I am trying to set up PiranhaCMS on an existing application. I have installed the package via nuget and everything seems to be in order.

I created a sql server db and set up the connection string.

The problem is that when I try and start the application I get an error saying Invalid object name 'sysparam'. 

I am assuming this is because the db has not been set up yet. But I cannot navigate to /manager to install the tables.

'''
[SqlException (0x80131904): Invalid object name 'sysparam'.]
   System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +1787814
   System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) +5341674
   System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) +546
   System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) +1693
   System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() +61
   System.Data.SqlClient.SqlDataReader.get_MetaData() +90
   System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) +377
   System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) +1421
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) +177
   System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) +53
   System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) +137
   System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) +41
   System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) +10
   Glimpse.Ado.AlternateType.GlimpseDbCommand.ExecuteDbDataReader(CommandBehavior behavior) +334
   System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior) +10
   Piranha.Data.ActiveRecord`1.Query(String query, Object[] args) +501
   Piranha.Data.ActiveRecord`1.GetFields(String fields, String where, Object[] args) +1482
   Piranha.Data.ActiveRecord`1.GetSingle(String where, Object[] args) +84
   Piranha.Models.SysParam.GetByName(String name) +350
   Piranha.WebPages.WebPiranha.RegisterDefaultHostNames() +103
   Piranha.WebPages.WebPiranha.Init() +200
   Piranha.Web.ApplicationModule.Start() +67
'''

**Comment by tidyui** [comment]
Hi there! Sounds weird, like the framework thinks that the tables have been installed. are you using the latest version from nuget?

**Comment by NickOhara** [comment]
Yeah, I'm using version 2.2.5.

I decided to manually run the SQL scripts provided on github, but that has caused more issues than before.

**Comment by EddyCwdry** [comment]
I'm also getting this issue, it's a new install with nothing extra added, just pointed it to the DB server and now i'm getting this error.

**Comment by danielkillyevo** [comment]
having the same issue...
is there any workarounds to resolve this?
cc: @tidyui @NickOhara @EddyCwdry

**Comment by danielkillyevo** [comment]
In my case I was able to resolve this disabling the **showDBErrors** setting:
<showDBErrors value="false" />
