### ISSUE TITLE
Issue when Composing External Entities (ExtensionManager)

### ISSUE THREAD

**Issue by mike-jewell** [PiranhaCMS/Piranha#430]
I've created a version of the Redis cache solution, which uses Newtonsoft.Json and StackExchange.Redis to avoid any issues (separate from this, willing to share if interested).  Since implementing and using the Redis cache, I have seen an issue when starting up our application, with a cryptic error around the ExtensionManager and IsLocked.

After debugging around the solution I have found the problem.  It is around the the Composing of the External Extensions we have created, and the error appears where the computed property IsLocked is used:
1. Piranha\Entities\Internal\PageTemplate
2. Prianha\Entities\Internal\PostTemplate

The computed property is making the call to Extend.ExtensionManager.Current.PageTypes/PostTypes, but the Compose method is still building the application from the previous call to Extend.ExtensionManager, which causes (somehow) a NullReferenceException.

Hopefully I am making sense....

Anyway, the problem isn't visible through the default WebCacheProvider because it just stores the PageType/PostType with a IsLocked having a NullReferenceException.  However, when serializing to Json the NullReferenceException is not appreciated and the system falls down.

I have a solution.  But before I submit a pull request, I want to make sure I am doing the right thing, as I  am not 100% sure about the circular reference on start up.  The chain of which seems to be:
1. ExtensionManager.ExtensionManager()
2. ExtensionManager.Compose()
3. ExtensionManager.OnImportsSatisfied()
4. ExtensionManager.EnsurePageTypes()/ExtensionManager.EnsurePostTypes()

Each of these calls on step 4 will result in the call to IsLocked on the PageType/PostType, which in turn call ExtensionManager.Current which appears to call ExtensionManager.ExtensionManager() (but that could just be Visual Studio) or is null.

My solution is to just change the property to:

```
public bool IsLocked {
    get {
        if (!String.IsNullOrEmpty(Type))
            try
            {
                return Extend.ExtensionManager.Current.PageTypes.Where(pt => pt.GetType().FullName == Type).SingleOrDefault() != null;
            }
            catch(NullReferenceException)
            {
                return false;
            }
            return false;
    }
}
```

Is this appropriate for the chain of events?  Or am I going to create a problem somewhere else?

**Comment by mike-jewell** [comment]
Also, network latency on the manager section is slow in azure Redis.  Is Redis as an azure cache viable for this version of Piranha?  Wondering if their are too many calls for a given object, and if this is a consideration for the next version.  

The site renders pages quickly with Redis, it is just the manager section.

**Comment by tidyui** [comment]
Hi there! Try your lock solution out for a while and let me know how it works. In regards to the Redis cache I have never tried it and I didn't write the code with it. Maybe @bapti has any thoughts on this since he contributed it!

**Comment by mike-jewell** [comment]
Hi, I've been using it for the day and it has not had any issues, will keep it going for the reset of the week and com back to you.

I don't think the Redis libraries are the issue, I think it is the number of calls to the ICacheProvider which is causing hi network latency issues.  I still need to keep investigating, but caching is a pain to get right over a network.  We have seen 7k cache hits and bandwidth hitting 380kb/s in Redis while 1 user was testing the manager section, with page loads of 5-8 seconds.  It wasn't a large number of page calls either.

Will keep investigating, want to make sure the assumption of calls to the ICacheProvider are the issue, I recognise the issue from another project I did in the past.

**Comment by tidyui** [comment]
Just checking up what happened with this issue @mike-jewell since I'm in the midst of releasing a new version. Did you find out anything else about your issue?
