### ISSUE TITLE
Custom entity troubles

### ISSUE THREAD

**Issue by timc22** [PiranhaCMS/Piranha#431]
I'm trying to follow the custom entity instructions listed here:
http://piranhacms.org/docs/extend/custom-entities

But I'm having some trouble getting it to work, because of what the example leaves out.  I figured out that the first ellipsis in the cshtml example (3.1) was supposed to be the actual class name of the custom entity model, but I don't know what the second ellipsis is supposed to contain:

@ foreach (var prod in ...) {

I know it can't be the model, since it isn't IEnumerable.  What am I supposed to put there to loop the collection of entities?

I'm not generating a runtime error from any of this yet, since I haven't been able to add it to the manager menu.  I tried to follow the next set of instructions:
http://piranhacms.org/docs/extend/manager-menu

The problem is that App_Start.cshtml doesn't appear to exist anymore, and none of the startup files (Global.asax, the cs files in the App_Start folder) have anything called "manager" in scope.  If I let the resolver path it to Piranha.WebPages.Manager, it doesn't error, but it also doesn't add anything to the menu either.  I'm pretty sure I shouldn't be using Piranha.WebPages anyway, since this is the MVC version.

I could probably build this with just custom page types, but I liked the idea of using a custom entity (and a custom edit view) so I could write something to import a flat data file, since this part of the application is going to have thousands of records.

**Comment by tidyui** [comment]
Hi there. Like you say, the pages you reference above are examples and leaves out certain things for you implementation.

### List page model

The model of the list page should be what your controller action returns, it can be an enumerable of items or another model that suits your need.

### Enumeration

Since the example is a list page it is assuming that **either** the model is an enumerable **or** that the model contains an enumerable property. 

### Menu setup

App_Start.cshtml is not available for ASP.NET MVC, use Global.asax and the Application_Start event. You're right that you should use `Piranha,WebPages.Manager` to access the menu, **however** the menu example uses a **custom permission** as an example to prohibit access to the new menu item. If you just copy & paste the example code the menu item will not show up as you will not have the permission added into your installation.

**Comment by timc22** [comment]
Thanks for such a quick response, but I'm afraid things aren't going too well...

I'm trying to figure out ASP.NET MVC at the same time as I'm figuring out how to use this CMS, so not having a demo example of a model is really making this difficult.  The model I generated was default/empty, so it makes sense that it wasn't enumberable, and there wasn't anything enumberable inside it.

I had commented-out the custom permissions described in (2. Adding the controller) from the start, and I had the code running in Global.asax's Application_Start event, but nothing appeared in the menu.  I should have mentioned that, sorry.

I still haven't been able to make any of this work yet, but now I have an even bigger problem.  After I followed the next step in the tutorial and told Visual Studio to generate an Edit view for my default model, the entire manager system broke.  After you login, it throws up a compilation error, saying "The name 'Styles' does not exist in the current context", complaining about line 7 in Areas\Manager\Views\Shared\_Layout.cshtml.  I have no idea why generating an edit view for an unrelated model would cause anything to happen in _Layout.cshtml.  I've even tried removing every single file I've created up to this point, and every reference to them, but it still won't come back.  Somehow this has corrupted the installation.  Should I avoid using Visual Studio's scaffolding entirely?

**Comment by tidyui** [comment]
Hi there! First of all MAKE SURE the worthless scaffolding hasn't generated a Layout.cshtml file in the Manager Area. This shouldn't exist in your project since the manager UI is embedded in the Piranha DLL.

Secondly, just take a look at the manager controllers, models and views for the manager interface here at GitHub as reference. The Params views are fairly simple, and the SiteTree views uses Entity Framework.

Regards

**Comment by timc22** [comment]
There indeed was a Layout.cshtml file there, and after I deleted it, things started showing up again.  But I'm still not making much progress on getting this new entity to work.  

I've made the class ienumerable, and resolved some weirdness with getting a listing page to show up (like having to fully specify the class names instead of using "var"), but my first steps on getting an insert view to work are giving me strange errors.  Right now it's saying "Object reference not set to an instance of an object" on the line in my Insert.cshtml file that tries to access @Piranha.Resources.Global.ToolbarBack.  If I remove that line or just replace it with the word "Back", I the error moves to the line above it that tries to access TollbarSave.  Remove that, and then it says @Html.Partial("Partial/Tabs") is not set to an instance of an object.  

Somewhat related: even though NuGet says Entity Framework was installed along with Piranha, I don't see any options to add Entity Framework items anywhere in Visual Studio.  Am I not understanding how to use NuGet packages, or has Entity Framework changed a lot since I last used it?  I remember there being a file that showed the whole database structure, and you could do things like generating classes from tables or synchronize the model with any changes in table structure.  I'm starting to think there's a lot of stuff I'm missing here about how to get custom entities working in Piranha.

**Comment by timc22** [comment]
Okay, I gave this another go, and I might be closer to my goal, or maybe just farther away.  I deleted what I had and started over with following a guide on getting an edmx set up correctly with the table I wanted to edit.  Here's what I have:

Web.config	
	<managerNamespaces value="MY_MVC_Piranha" />

CustomEntityModel.edmx > CustomEntityModel.tt > company.cs
	namespace MY_MVC_Piranha
	{
		using System;
		using System.Collections.Generic;
		
		public partial class company
		{
			public int CompanyID { get; set; }
			public string Name { get; set; }
		}
	}

Controllers/CompanyController.cs
public class CompanyController : ManagerController
        public ActionResult Index()
        {
            return View(db.companies.ToList());
        }
	

Areas/Manager/Views/Company
	Create.cshtml
	Delete.cshtml
	Edit.cshtml
	Index.cshtml


Global.asax > Application_Start:

            Manager.Menu.First().Items.Add(
                new Manager.MenuItem(){
                    Name = "Companies",
                    Action = "Index",
                    Controller = "company",
                    SelectedActions = "companylist,companyedit"
                });

RESULT:
	A "Companies" button appears in the manager, which directly links to the path /manager/company, which produces the error:
		The resource cannot be found.

I tried renaming some of the generated names to more closely match the naming schemes that the demo suggested (stopped entity from using the plural "companies" and stuff like that) and propagated those name changes as well.  So there's no build errors, everything looks fine, but I still can't get to a listing page.  I put two items in the database manually, in hopes that the index view would show them, but no dice.  I still can't even get to the index view.

**Comment by timc22** [comment]
Only one weird thing still happening with my custom entity... the admin page /manager/company isn't rendering anything for the line:

@ Html.Partial("Partial/Tabs")
(space added to not be a user mention on github parsing)

Nothing gets rendered for that line, but the normal admin header is still present.  So you can navigate from pages or posts to companies, but you can't get back since that menu goes away.

**Comment by timc22** [comment]
Another issue: the javascript search box for content (on the admin/manager pages) stops working correctly after you reach a certain number of records. It will never show the items toward the bottom of the list (even if you're searching for them) and then doesn't return them to the page after you clear your search filter.

**Comment by tidyui** [comment]
Your comment on the user list has been added as issue #467. I will close this issue for now
