### ISSUE TITLE
Problem with GroupDocs.Viewer for .NET

### ISSUE THREAD

**Issue by riverstore** [PiranhaCMS/Piranha#432]
Hi! I tried to use GroupDocs.Viewer for .NET to a project which use Piranha. And I alway get this error message:

http://pastebin.com/KLTTzqw8

Can anyone please help me. Thanks a lot.

**Comment by tidyui** [comment]
Yes some external components just doesn't seem to work with MEF. Good news is that a lot of options were added in the latest version to deal with such problems. Take a look at the docs on configuration!

You can for example stop MEF from scanning external assemblies, or you can compose the application totally manually if you like.

**Comment by riverstore** [comment]
Hi! Thanks a lot for answering, I just download Piranha 2.2.5 and still get the same error. Please give me some tips to solve this issue. Thanks a lot.

**Comment by tidyui** [comment]
Have you tried the different settings described here:

https://github.com/PiranhaCMS/Piranha/wiki/Configuration

Or manual composition as described here:

https://github.com/PiranhaCMS/Piranha/wiki/Composition

**Comment by riverstore** [comment]
Hi! Set disableComposition to true solved the problem. Thanks a lot.

**Comment by tidyui** [comment]
Yes I'm sure BUT unless you perform manual composition you won't have access to ANY regions and other parts so it will crash nevertheless. Did you read the article about composition ?

**Comment by riverstore** [comment]
Hi! Thanks a lot for notice me. After commenting out lines as said above, I just check overall the manger section, and found that some pages can't be accessed like 
http://localhost:12968/manager/settings/user/30e4b123-ae14-4cdd-a061-d7c4d1bbc079

Error

http://pastebin.com/i76QtfVd

I'm using 2.2.4 and have made a lot of change to the "core" so I don't want to move to 2.2.5 now. Can you please help me to solve it? Thanks a lot.

**Comment by tidyui** [comment]
Please verify if this option exists in 2.2.4

    <disableCatalogSearch value="false" />

It makes sure only Piranha DLLs are used when composing

**Comment by riverstore** [comment]
Hi! look like that 2.2.4 doesn't support disableCatalogSearch

Unrecognized element 'disableCatalogSearch'. (G:\code\CSharp\Piranha-2.2.4\TemplateSite.Mvc\web.config line 17)

**Comment by riverstore** [comment]
Hi! I think I have to move to 2.2.5. Does the database's scheme of 2.2.4 and 2.2.5 are same?

**Comment by riverstore** [comment]
Hi! I moved to 2.2.5 now, I set <disableComposition value="true" /> and copy this to Global.asax.cs

Piranha.Application.Compose(c => {
  c.RouteHandler = new Piranha.Mvc.RouteHandler();
  c.Framework = new Piranha.Mvc.ClientFramework(); 
});

But I don't know where to place

Piranha.Extend.ExtensionManager.Compose(c => {
  // Add standard regions
  c.Extensions.Add(Piranha.Extend.Regions.AttachmentRegion());
  c.Extensions.Add(Piranha.Extend.Regions.HtmlRegion());
  c.Extensions.Add(Piranha.Extend.Regions.ImageRegion());
  c.Extensions.Add(Piranha.Extend.Regions.MarkdownRegion());
  c.Extensions.Add(Piranha.Extend.Regions.PostModelRegion());
  c.Extensions.Add(Piranha.Extend.Regions.PostRegion());
  c.Extensions.Add(Piranha.Extend.Regions.TextRegion());

  // Example on how to add custom page types
  // c.PageTypes.Add(new MyProject.PageTypes.BlogPage());

  // Example of how to add custom post types
  // c.PostTypes.Add(new MyProject.PostTypes.BlogPost());
});

Now I got this error on access to add new, edit object in managers (Ex: http://localhost:12999/manager/page/edit/af94881c-ebeb-4c2c-a899-200187e1866a)

http://pastebin.com/0RFmW5jP

Please help me. Thanks a lot,

**Comment by riverstore** [comment]
Please help me, now I don't know where to continute :(. Thanks  alot.

**Comment by tidyui** [comment]
You compose the extension manager AFTER the application in you Application Start. By doing this the error will go away

**Comment by riverstore** [comment]
Can you please give me more detail?  Thanks a lot.

**Comment by tidyui** [comment]
The code you didn't know where to place should be placed directly under the code you pasted into your Global.asax.cs

**Comment by riverstore** [comment]
Thanks! But now I got this error messages :(

Error	19	'Piranha.Extend.Regions.AttachmentRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	60	34	ezLib
Error	20	'Piranha.Extend.Regions.HtmlRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	61	34	ezLib
Error	21	'Piranha.Extend.Regions.ImageRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	62	34	ezLib
Error	22	'Piranha.Extend.Regions.MarkdownRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	63	34	ezLib
Error	23	'Piranha.Extend.Regions.PostModelRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	64	34	ezLib
Error	24	'Piranha.Extend.Regions.PostRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	65	34	ezLib
Error	25	'Piranha.Extend.Regions.TextRegion' is a 'type', which is not valid in the given context	G:\code\CSharp\Piranha2.2.5\Templates\TemplateSite.Mvc\Global.asax.cs	66	34	ezLib

**Comment by tidyui** [comment]
I see there's a typo in the example. It's supposed to say 'new' before all of the types!

Regards

**Comment by riverstore** [comment]
You save my life again ^^. Thanks a lot!
