### ISSUE TITLE
E-mail address as login name

### ISSUE THREAD

**Issue by blaataap** [PiranhaCMS/Piranha#433]
Hi,

The Core now only has a possibility to login with username and password, would there be a way to extend this option and make it possible to login with E-mail address and password? Or do i have to write my own methods?

Thanks

[edit] Crap, this should be flagged as question[/edit]

**Comment by Lucstar** [comment]
Hi, it sure works for me in version 2.2.4. 
The username is an email thought. Do you mean you want to be able to log in with user.email OR user.username?

**Comment by blaataap** [comment]
I want to register both username and email but logging in should be with user.email. Ill use the username for display references only.

**Comment by tidyui** [comment]
Hi there! The standard login method uses username + password for authentication. If you want to change login you can just add your own login method, the code for the standard login can be found here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Entities/Internal/SysUser.cs#L198
https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Entities/Internal/SysUser.cs#L198

Regards
