### ISSUE TITLE
Using edited piranha dll (core\piranha) in Templatesite\bin not working in IIS publish 

### ISSUE THREAD

**Issue by karthikthangavel** [PiranhaCMS/Piranha#434]
I am trying to edit the "core\piranha" project with adding new class file to write log for getting current application path and physical path of current request when URL() method is calling in "web\UIHelper" class.

Buts its just work fine in local. When publishing in IIS its not working.

Its working when browse for page.cshtml physical file.

**Comment by tidyui** [comment]
Hi there. Since I really don't know what you've done I can't really help you with your modified version of the framework. If you want to be able to share your code to get help, please keep it in a public **fork** here at GitHub and you can always link to your modifications.

Regards
