### ISSUE TITLE
RSS items doesn't show

### ISSUE THREAD

**Issue by Lucstar** [PiranhaCMS/Piranha#435]
How do I activate the RSS? on all my installation the "/rss" does not include any pages or posts. On Posts it is possible to "include in rss", but that doesnt seem to help. version 2.2.4.1

Regards Luc

**Comment by tidyui** [comment]
Have you selected "Include in Rss" on the post type? Also if it wasn't selected before and you've changed it to be activated, check settings on individual posts. They might still be disabled for RSS export.

**Comment by tidyui** [comment]
Did you work this out or do you have any further questions @Lucstar?

**Comment by Lucstar** [comment]
Hej Håkan, 
No luck with this. Followed your descriptions but still no. 

http://www.ostgotamarknader.se/rss
http://www.lindovilla.se/rss 

Thanks
/Luc

**Comment by Lucstar** [comment]
Is there other parameters for the RSS then RSS_NUM_POSTS = 0 and RSS_USE_EXCERPT = 0? 
In some installations i do not have all parameters, thats why i ask.

**Comment by Lucstar** [comment]
Found out that posttemplate_rss in table posttemplate was not set. I changed it in the db. Since i run with code first i can save in the UI, and seems i can-t sett AllowRss in the code. Close Issue.

**Comment by tidyui** [comment]
I'll include so that this can be set through code in the upcoming release.
