### ISSUE TITLE
Adding Piranha to existent MVC

### ISSUE THREAD

**Issue by erdvillegas** [PiranhaCMS/Piranha#437]
Hello,

I'm trying to integrate piranha to an existing MVC application, it has been done, I've followed the installation guide, I'm able to navigate through the manager also open the cms content, so, when I try to use the MVC controller I've received an not found issue, I've made some configuration but when I disable the permalink MVC works, unfortunately CMS doesn't work (and vice versa),

Is there any way to allow both MVC and CMS working together as an hybrid application?

**Comment by Eonasdan** [comment]
@erdvillegas that's actually one of the best parts about this CMS is that you can add it to existing projects.

Try adding [this nuget package](https://www.nuget.org/packages/routedebugger/) and turn Route Debugging on in the Web.config file. It will append the routes that got tried at the bottom of the page (even 404).

Post a picture here with the route debugging info.

**Comment by tidyui** [comment]
Hi there, If your controller inherits from either **SinglePageController** or **SinglePostController** you have to access CMS data by the **permalink URL** and not directly through controller/action. If you don't do this the base class will not work.

Regards

**Comment by erdvillegas** [comment]
So, I've inherited from Piranha's Base controller in order to make a common MVC beahvior or Page / Post controller to get CMS content?

**Comment by tidyui** [comment]
The SinglePage & SinglePost controllers adds base functionality to retrieve the currently requested content by its permalink. It assumes that the current request has passed through the CMS routing and has passed on a query parameter with the name `permalink`. You can see how it's used in the standard MVC template.

https://github.com/PiranhaCMS/Piranha/blob/master/Templates/TemplateSite.Mvc/Controllers/PageController.cs#L22
https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha.Mvc/SinglePageController.cs

If you don't want to use the built in routing for pages your should not inherit from these controllers.

**Comment by tidyui** [comment]
Did you work this out @erdvillegas or do you need further assistance?

**Comment by erdvillegas** [comment]
Thanks alot, Hi just integrate the CMS adding a new page type in order to just add all MVC routes here.
