### ISSUE TITLE
Can we use Markdown for posts?

### ISSUE THREAD

**Issue by hades200082** [PiranhaCMS/Piranha#439]
I've been trying to setup a site and I want all content to be edited as markdown... but it seems like the posts editor only has HTML region?

Is there any way I can make it use Markdown instead?

**Comment by tidyui** [comment]
Hi there! An easy way to achieve this would be to create a post extension that inherits from the markdown region and call the region view from the extension. You could then hide the default post body either with JavaScript or just override the post edit view in your project

**Comment by tidyui** [comment]
Another solution is to add a local implementation of the HtmlEditor which is in `~/Areas/Manager/Views/Shared/Partial/TinyMce.cshtml' and add whatever editor you want.

You could then implement the following **hook** and transform the markdown into html before rendering.

    Piranha.WebPages.Hooks.Model.PageModelLoaded += (model) => {
       // Transform markdown content into html
    };
