### ISSUE TITLE
HTTP Error 404.0 - Not Found on New Project

### ISSUE THREAD

**Issue by Gareth2015** [PiranhaCMS/Piranha#440]
Hi Håkan,

I'm getting a 404 error when trying to access any pages on my site.

I've created a brand new empty (no MVC templates or anything) project in VS, installed the NuGet package and tried to fire the site up (after amending the connection strings).

Everything installs and then I get an Null Object Reference error. Stopping debugging and restarting gets rid of this error.

When restarting, the managers pages all work but the pages fail to load with a 404 error.

The requested url looks ok:  http://localhost:53745/page/?permalink=home&piranha-culture=en-US

However the physical path seems to be off: c:\users\SomeUser\documents\visual studio 2013\Projects\Project1\Project1\page\

Is there anything I'm doing wrong?

Thanks

**Comment by tidyui** [comment]
Hi there! Well the first error that you got after making the installations in a known bug, see #417. The 404 error feels like either the controllers or views included in the MVC template are missing. Do you have the files:

    Controllers/PageController.cs
    Controllers/PostController.cs
    Views/Page/Index.cshtml
    Views/Post/Index.cshtml
    Views/Shared/_Layout.cshtml

Also, are you getting a **404** from the web server or from ASP.NET, cause if you're getting it from ASP.NET, disabling `CustomErrors` in your web.config might give a more detailed error description.

Regards

**Comment by Gareth2015** [comment]
Thanks for the quick response.

Checking around the application, the global.asax file is missing. I've tried adding it registering the routes normally (as per other working projects) to no avail.

WIll get back once I turn off custom errors and let you know the output thanks.

**Comment by Gareth2015** [comment]
I've managed to solve the issue with the following steps:

1. Added global.asax file to the application
2. Modify markdown for global.asax to point to inherit the MvcApplication
3. Modified the web.config file in the Views folder with a copy of one from a different application that already has Piranha installed (amending the namespaces).

Hope this helps for future?

**Comment by tidyui** [comment]
Well I have heard of situations before where all of the files of the NuGet-package just hasn't been installed properly into the project, but it's almost impossible to debug these issues as there's really no clear way of reproducing it. Anyway I'm glad it worked out!

**Comment by Gareth2015** [comment]
It's a weird one! Hope it helps someone else in future - just a bit concerning if someone's never used piranha (which I must say is a brilliant piece of kit)
