### ISSUE TITLE
Null Reference Exception, SinglePageController with separate authentication handler

### ISSUE THREAD

**Issue by eplewis89** [PiranhaCMS/Piranha#441]
Hey Piranha Devs,

I was reading up on issue #274 and I was having the same issue, but my question deviates from the OP of #274.

You asked about being authenticated from HttpContext but not with a user associated with Piranha (https://github.com/PiranhaCMS/Piranha/issues/274#issuecomment-40699608)

My answer to this is yes, I'm logging in through a separate membership authentication methodology, and I'm experience this bug. In our code, we are overriding the OnActionExecuting method of the System.Web.MVC.Controller class in a "membership" area which handles login for users associated with the website. How can we handle the case where a user is logged in, but not associated with Piranha?

**Comment by tidyui** [comment]
Hi there! Check out issue #177 where we did a work around for letting Piranha run side-by-side with an existing authentication and let me know if it applies to your scenario!

Regards

**Comment by eplewis89** [comment]
We found a workaround for the gim
