### ISSUE TITLE
.NET 5 / ASP.NET MVC 6 support?

### ISSUE THREAD

**Issue by dotnetshadow** [PiranhaCMS/Piranha#442]
Hi I was wondering if you will have support for .NET 5 / ASP.NET MVC 6 support?

**Comment by tidyui** [comment]
Hi there! Yes I normally try to upgrade the framework to the latest versions, however I also tend to wait until after they are released. I've looked into the new ASP.NET runtime before, but at that time it was too much beta state to do any upgrades. Also I might hold off until Entity Framework 7 is released as I would really like to go all in on being able to release the framework for the new Cloud runtime.
