### ISSUE TITLE
Delete pirahna-db from sqlexpress  and not working now

### ISSUE THREAD

**Issue by rahulrustagi** [PiranhaCMS/Piranha#446]
Hi,

I was trying to run CMSMVC web application, use PM to install the MVC web application. I tired to run it, it executed and db was created in sqlexpress version using integrated security. But somehow i dropped the database using windows authentication. Now when i try to run the application it give me error "Cannot open database "piranha-db" requested by the login. The login failed.
Login failed for user NTLOGIN".

What should i do to resolve it?

**Comment by tidyui** [comment]
This is almost impossible for me to say. I have little control over the database. .NET is pretty keen on storing connections in an internal connection pool for performance reasons even if the connection is dead. But this should have sorted itself out by now as the connection pool is cleared when the application is recycled.
