### ISSUE TITLE
Remove MySql support

### ISSUE THREAD

**Issue by tidyui** [PiranhaCMS/Piranha#455]
As usage of this is very small, and it's a hassle to support two database schemas, MySql support will be dropped as of 2.2.6. It might be included when schema creation is moved to Entity Framework.

**Comment by Rathje** [comment]
Hi tidyui,
First of all thanks for a great product. I have a previous version installed fine with MySQL. But recently I installed another and newer version, where it seems to not be able to use MySQL. I have set up provider exactly as the old one, but still it breaks with error during create process.
Would this be solved if I could use a initial schema? And where do I find one?
Best regards
Lars

**Comment by tidyui** [comment]
Hi there! Unfortunately I had to drop the support for MySql as usage was very limited and I had no good way of testing & keeping it updated. Like you say you can create the schema (with some modifications) manually by executing the create scripts **but** if my memory serves me correctly there were some special handling in the code as well as MySql handled certain data types differently.

In other words, if MySql is a key feature for you there's no safe upgrade path for version `2.2.6` and above.

Regards

Håkan

**Comment by Rathje** [comment]
All right. But thanks anyway for your response.
I think I will try to work on converting the sql scripts to see if I can get it setup. Once it's setup it seems to work fine using the entity framework.
Thanks again

**Comment by Rathje** [comment]
Hi once more,
I ended up to stick with version 2.2.5. Both installs works fine in this version for now.
But actually I thought the whole idea of shifting to EF6 is to make the solution database independent? Do you really need to use specific MySql codes under this framework? Will Piranha vNext solve this in the future?
Best regards Lars

**Comment by tidyui** [comment]
The [Piranha.Core](http://github.com/piranhacms/piranha.core) repository currently uses `Dapper` for maximum performance. The database schema has been simplified even more so that it will run perfectly on SQLite. I haven't done any tests on MySql so far but I can look at it further down the road.

Regards

**Comment by aatmmr** [comment]
In case anyone is interested - I wrote a short tutorial on how to use Piranha Core with MySQL which you can find at [my GitHub Repo](https://github.com/aatmmr/piranha-core-mysql). As I proceed I will add comments and experiences that might be of interest.

Cheerio!

**Comment by tidyui** [comment]
This is awesome, I’ll post a link to it from our Twitter account! However, you might want to add this issue in the piranha.core repo as this is the repo for the old legacy version.

Also, in your README you mention version 2.7.x but this is not correct as it’s the version for the old legacy non core version. The AspNetCore version starts at 4.0 and is currently at 4.3.1.

Best regards!

**Comment by aatmmr** [comment]
Thanks a lot and I am happy to contribute 🎉  

I fixed the - embarrassing - version mistake 🤦‍♂️ and added a new issue to the [piranha.core repo](https://github.com/PiranhaCMS/piranha.core/issues/269).

Cheerio!
