### ISSUE TITLE
Object reference not set to an instance of an object - when integrating to an existing MVC site.

### ISSUE THREAD

**Issue by evak2979** [PiranhaCMS/Piranha#468]
Object reference not set to an instance of an object.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.NullReferenceException: Object reference not set to an instance of an object.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[NullReferenceException: Object reference not set to an instance of an object.]
   Piranha.Config.get_SiteTree() +52
etc.

Any help or direction wouldbe appreciated :/

**Comment by tidyui** [comment]
If you just installed the database it's probably a duplicate issue #417 which will be resolved in the next release. If you save your web.config the cache is cleared and the application will start normally.

**Comment by evak2979** [comment]
Thank you but my next problem is more serious...  I can't get it to work
with owin identity :(.  It clashes with forms authentication.

**Comment by tidyui** [comment]
No, the current version of Piranha CMS doesn't integrate with other forms of authentication. However you should be able to configure requests for `/manager/...` to use forms authentication and use identity for the rest of the site.

**Comment by evak2979** [comment]
I can try and see but I worry that enabling the module for form will
disable owin as a whole...  I will let you know :)

**Comment by vurso** [comment]
Has this been resolved as I am experiencing the issue with latest version (did a clean install on a fresh SQL Express DB, all goes well during set up however logging in causes a problem).

I haven't debugged but will dig into it later hoping someone has a quick solution.

**Comment by vurso** [comment]
Issue #417 resolved the issue for me (edited web.config saved it then rebuilt the solution after doing the db install).
