### ISSUE TITLE
Adding to existing site - how to determine site ID ?

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#470]
I'm adding Piranha to an MVC app which has some dynamic content determined by the URL the user uses. I have added two new Sites inside Piranha which will hold the different site layouts for the two brands.

When I load my Page Model up in the controller I use GetByPermalink but when I do this var x = Piranha.Models.Page.GetByPermalink("homepage"); the SQL it uses tries to match on the Default Site. How does Piranaha try to determine which site I am accessing (does it try matching on the Host Name ?) and can I override this by explicitly setting the Site as part of my GetByPermalink call code ?

The reason for the question is that I have a site whose HostName is "xyz" and I'm starting my application in VS.net as "http://localhost:238472/xyz" - my routing picks up my home page (I'm working in passive mode) and I expected GetByPermalink("homepage") to work and fetch the page of that Permalink on the xyz Site - but it keeps trying to find the page on the default site. 

I am a bit confused by the documentation - the Permalink I see displayed in the manager application has a full URL in it, including some kind of prefix "http://...../home/homepage" - am I supposed to use this entire URL as by GetByPermalink value ? Or just "homepage" or "home/homepage" ?

**Comment by PhillipHamlyn** [comment]
I answered my own question by looking in the source code. The hostname in the Site definition must match the HttpContext.Request.HostName in the current web call. This is quite inflexible - I would have wanted the ability to directly set the current site based on my own logic, rather than using the HttpContext for this.

**Comment by tidyui** [comment]
Yes you are totally, right, but there actually exists a version of that method that takes the sitetree Id as a parameter.

    public static Page GetByPermalink(Guid siteTreeId, string permalink, bool draft = false)

If you want the full page model you can then get the model from that page instance!

Regards
