### ISSUE TITLE
cant add a view using razorgenerator

### ISSUE THREAD

**Issue by lsvosve** [PiranhaCMS/Piranha#471]
how do i add a custom view on the cms, its giving me issu
![piranha](https://cloud.githubusercontent.com/assets/16881133/12553857/6613b012-c382-11e5-803c-1484b2bc0268.png)
es

**Comment by tidyui** [comment]
You will have to clarify what exactly you are doing to get that error message!

Regards

Håkan

**Comment by lsvosve** [comment]
i have created a custom controller, and model in the manager area and in trying to add a view for the controller that is when i get that error, i am adding the view by right clicking on the controller and select add view , or maybe i would need to know how to add custom views. i am trying to see how i can extend it into a web application, because i like the way its designed and it being light weight

**Comment by tidyui** [comment]
Here are two articles on how to:

1. How to add a custom entity and then add a controller & view in the manager for it.
2. How to extend the manager menu in you application to include the a new view.

I hope this helps!

* http://piranhacms.org/docs/extend/custom-entities
* http://piranhacms.org/docs/extend/manager-menu

Regards

Håkan

**Comment by lsvosve** [comment]
thank you very much for helping, i am finding it very helpful, this is a
nice project.

Regards

L Svosve
