### ISSUE TITLE
Enforcing default value for Properties

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#473]
If I define a  PageType in code, and add some Properties, then try and use these in a Razor like this;

@Html.ActionLink((string)Model.CMSData.Properties.WebSiteTitle, "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })

I find that if the user has not entered a value for this property, then the Properties returns an empty Expando object with a result of a NullReferenceException. I have to cast to string to force Razor to select the correct overload.

Since Properties are all of type String it would be more helpful to return an empty string to prevent having to check for null all over the place.

**Comment by tidyui** [comment]
I most definitely agree, this is the way it works for **regions** so properties should be treated the same way.

**Comment by tidyui** [comment]
This is quite weird. When the `PageModel` is created the Properties are initialized here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Models/PageModel.cs#L66

Then when the model itself is initialized the properties from the **PageType** is looped first, initializing all defined properties with an empty string before the values are retrieved.

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Models/PageModel.cs#L275

So by just looking at the source code, it **should** do the correct thing. I'll have to debug to see if I can reproduce the issue.

Regards
