### ISSUE TITLE
adding custom scripts

### ISSUE THREAD

**Issue by lsvosve** [PiranhaCMS/Piranha#476]
The issue i have is, if i put a custom script  under content folder then reference it as shown on the image below it doesn't come out

what should i do?

all my resources are embedded resources 

![issue](https://cloud.githubusercontent.com/assets/16881133/13002963/2e82f6ec-d17b-11e5-9611-5123f5128c54.png)

**Comment by tidyui** [comment]
Hi there! the handler `res.ashx` is **only** used for retrieving assets embedded within `Piranha.dll`. Since you've added your script to your local application it's located on disc and should be retrieved with a standard asset url.
