### ISSUE TITLE
migrating databases

### ISSUE THREAD

**Issue by Wintyswilly** [PiranhaCMS/Piranha#478]
I want to migrate data from one CMS on (Ombraco) sql server to piranha CMS sql server.

They are both similar (not exact by any means)... before I go mad on mapping out the database completely.... Do you have any literature on that Piranha SQL sever database table structure? A diagram would be mega!!!

Obviously I'm very happy to share what I have done and how I did it if no one has done this before.

or if I have gotten migrating one cms to piranha all bent round my neck then by all means let me know!

Cheers

Winty

**Comment by tidyui** [comment]
Always hard to figure out how to respond to a person with a pair of orange speedos on his profile picture, but here it goes :)

I have never actually worked with Umbraco so I'm not familiar with it's database or content structure. As page content in Piranha (i.e Region content) is in fact JSON serialized CLR objects, just selecting data from Umbraco into Piranha might be complicated without first building up the proper content structure in Piranha to support it. If I were you I would do the following.

1. Setup your Piranha site to support your current content structure
2. Export data from Umbraco into some type of file (XML/JSON/whatever)
3. Write an import program that reads the above file, creates the Page Models and saves them to the database.

Doing it this way you will make sure that the saved data will be deserializable and usable.

Regards

**Comment by Wintyswilly** [comment]
Yeah I should probably not use random creepy pictures of Rod Stuart as my profile picture and then go firing of serious questions!

Awesome that seems like a more sensible approach! I will try that first! When I crack it I will send some detailed instructions in for you.

Regards

Winty
