### ISSUE TITLE
Change Request - Site Identification

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#479]
At present the HTTP re-write layer identifies the Piranha site using the hostname portion of the incoming HttpRequest. In many cases multiple Piranha sites may be hosted on the same IIS Instance under different Virtual Directories, and the mapping logic could only server one Piranha site per IIS Instance. The change request is to allow the CMS Admin to specify a MVC Route style syntax/regex/etc. to identify the site from the incoming Http Request URL to allow for multiple Piranha sites to co-exist on the same IIS server.

So instead of HostName the operator would specify "Partial URL". You will find this kind of syntax used extensively in IIS to specify URL matches for re-writing and other IIS modules.

This capability should also be able to be specified from the sites own RouteConfig.cs by calling an API into Piranha similar to this;

Piranha.MapSite(siteUrlSpecification, piranhaSiteName);

So this would mean Piranha would identify incoming Http requests either by the 'passive' registration of a URL match through the Manager interface, or alternatively, because it finds an 'active' match that its been registered with. Again this mirrors how IIS works with the ability to 'passively' register settings in the IIS Metabase or for an MVC/WebForms application to intercept this themselves 'actively' and configure their site behaviour in code.

**Comment by tidyui** [comment]
Interesting concept! Actually it works to register a sitetree to a partial url, for example `myhost.com/subsite` as well, but it's probably not documented correctly ;)

**Comment by PhillipHamlyn** [comment]
But I see in your code;

var hostname = HttpContext.Current.Request.Url.Host.ToLower();
if (HostNames.ContainsKey(hostname))
return HostNames[hostname];

Explicitly matching only the Host part of the RequestURL

**Comment by tidyui** [comment]
Not sure where you copied that code from, a link would be good :) This is the code that is run for incoming requests. Maybe there are some inconsistencies somewhere else?

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/WebPages/WebPiranha.cs#L278

Regards

**Comment by PhillipHamlyn** [comment]
WebPiranha.CurrentSite, which is used to support all the Razor helpers.

It works as you suggest in the WebRequest.

**Comment by tidyui** [comment]
That is not entirely true, if we look at the complete source code for the get accessor for `CurrentSite`

    // Check for configured site tree from the host name
    if (HttpContext.Current != null && HttpContext.Current.Request != null) {
      if (RequestedSite != null) {
        return RequestedSite.SiteTree;
      } else {
        var hostname = HttpContext.Current.Request.Url.Host.ToLower();
        if (HostNames.ContainsKey(hostname))
          return HostNames[hostname];
      }
    }
    // Nothing found, return default
    return DefaultSite;

Here we can see that the method first checks the property `RequestedSite`. This property is set in `BeginRequest` if you look at the previous link I sent. If for some reason this can't be found it falls back to its default behavior which most likely is the older version that existed before subfolders where supported.

As all code executed in a server request is executed after `BeginRequest` the property `RequestedSite` won't return null and return the current site tree based on hostname & subfolder.

**Comment by PhillipHamlyn** [comment]
Ok, I get that. So I can enter any portion of the site URL from Host all the way to the Virtual Directory, in the manager interface, and it will distinguish my specific site. That's great news. As you say - perhaps the docs could do with updating and the manager interface show some example "HostName" values. 

What is the mechanism for moving a site from one host to another - i.e. promoting a site from UAT to Live - is it just a matter of registering all the possible host names in the manager interface and restoring the CMS database from UAT over to Live ? i.e. can I do this 

HostNames = "localhost/MyDevSite" "LiveDomain/MyLiveSite" ? 

or is there a better method you would recommend. 

I'm happy to close my initial Issue - I had been blindsided by the HostName label in Manager and the use of Host in the code.

**Comment by tidyui** [comment]
There should be nothing in the database pointing to any specific location, so promoting the site should only involve deploying the web application & the database. I usually do it the way you did it in your example, i.e including both local & live hostname-setups in the database. Then you don't have to remember to reconfigure the live version after deploy ;)
