### ISSUE TITLE
Standard MVC Template with folder Home\About gives 404

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#480]
The Piranha PermalinkHandler registration 

"Handlers.Add("home", "PERMALINK", new PermalinkHandler());" 

clashes with the standard MVC template which creates a Home\About view. All references to the Home views are intercepted by the Permalink Handler and dont get routed to the MVC Controller creating a 404.

Request to make this re-routing optional (perhaps web.config driven, or by dynamic examination of the MVC routing table)

**Comment by tidyui** [comment]
You can either run you application with `prefixlessPermalinks` disabling the permalink keyword, **or** you can remove the permalinkhandler and then add it with another keyword of your choice, for example `cms`.

**Comment by PhillipHamlyn** [comment]
Works great, thankyou. Probably would trip up anyone creating a new MVC application.
