### ISSUE TITLE
STARTPAGE Permalink Handler intercepts parameterless URL

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#481]
Its common in MVC for the default route to have a default Home/Index pattern to deal with a parameter-less URL call. Piranha registers an HttpHandler using 

Handlers.Add("", "STARTPAGE", new PermalinkHandler());

Which maps all parameter-less URLs to a permalink handler for StartPage. The declared defaults on the MVC routing table are bypassed by this.

Request to make this re-routing optional (perhaps web.config driven, or by dynamic examination of the MVC routing table)

**Comment by tidyui** [comment]
The handler for the startpage can be removed from your application startup code (Global.asax.cs) with the following line:

    Piranha.Application.Current.Handlers.Remove("STARTPAGE");

**Comment by PhillipHamlyn** [comment]
Works great, thankyou.
