### ISSUE TITLE
Suggestion - support multiple Identities

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#482]
I use OWIN identity management in my application and switching from my application to Manager correctly asks me to login (Piranha uses Forms). This isn't a problem and I have no problem with the need to have separate logins between application users and content managers.

I noticed a problem under Https where the LocalUserProvider class was expecting to get a FormsIdentity back from the HttpContent.Current.User.Identity but in many cases it was getting a ClaimsIdentity. This caused it to refuse the login and keep cycling round the login form.

I locally modified the LocalUserProvider to add the following method;

```

 /// <summary>
        /// Piranha explicitly uses FormsAuthentication - this method is used to replace a calls to HttpContext.Current.User.Identity in this 
        /// module which would ordinarily return the users Idenity as an ClaimsIdentity, and the Name part of the ClaimsIdentity is the login name
        /// not the Forms Authentication Guid expected by Piranha. The OWIN and Forms can co-exist side by side, but when Piranha gets the users
        /// identity, it expects to get a Forms Identity.
        /// </summary>
        /// <returns></returns>
        private System.Web.Security.FormsIdentity extractFormsIdentityFromHttpContext()
        {
            if (HttpContext.Current.User != null)
            {
                System.Security.Claims.ClaimsPrincipal claimsPrincipal = HttpContext.Current.User as System.Security.Claims.ClaimsPrincipal;
                if(claimsPrincipal != null)
                {
                    return claimsPrincipal.Identities.OfType<System.Web.Security.FormsIdentity>().FirstOrDefault();
                }
            }
            return null;
        }
```

and use it like this;

```
/// <summary>
        /// Gets if the current user is authenticated.
        /// </summary>
        public bool IsAuthenticated {
            get {
                System.Security.Principal.IIdentity formsIdentity = extractFormsIdentityFromHttpContext();
                if (formsIdentity != null && formsIdentity.IsAuthenticated) {
                    try {
                        // Check if this user has a Guid id.
                        var id = new Guid(formsIdentity.Name);
                        return true;
                    } catch { }
                }
                return false;
            }
        }
```

This means the LocalUserProvider will always deal with the contexts FormsIdentity explicitly and has the happy side effect of allowing manager login to work under https.

Hope its a useful suggestion. (Full code attached)
[LocalUserProvider.Zip](https://github.com/PiranhaCMS/Piranha/files/148008/LocalUserProvider.Zip)

**Comment by tidyui** [comment]
Sounds great!! Make a **pull request** and I'll include it in the next release!
