### ISSUE TITLE
Best Practise ? Default values for Regions and Properties ?

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#485]
Hi,

Is it possible to define default values for Regions and Properties when using the IPageType extension. In many cases my user wont want to alter from the default text. I can see that I could put my default value in my Razor view and override with the value (if any) I retrieve from the CMS - is that the best way of going about this ?

**Comment by tidyui** [comment]
When a page is loaded from the CMS the proper CLR type for regions are always instanciated for all regions, even if the users hasn't added any content to them. This is of course to avoid NULL pointer exceptions in the views.

If a certain region should have default values you can always set these in the constructor for that extension object, however this means the default value would be persisted to the database. If you'd like to add a default value to a custom region at runtime if it's not populated you could either do this by overriding the following method in your extension and doing something like this:

    public override object GetContent(object model) {
      if (String.IsNullOfEmpty(MyStringProperty))
        MyStringProperty = "Default value";
      return this;
    }

Note that both these approaches only work for **custom extensions**. If you want to add default values to already existing regions/extensions in Piranha CMS you can always modifying them by adding code to the right **hook** in your startup code, for example.

    Hooks.Model.PageModelLoaded += (model) => {
      try {
        var region = model.Regions.MainContent;

        if (String.IsNullOrEmpty(region.GetHtmlString()) || region.GetHtmlString() == "<p></p>")
          region = "<p>This is the default content</p>";
      } catch {}
    } ;

As a note I might add that I wrote the above code here in the comment field and haven't compiled, so if there are any errors I'm sorry, but I hope you get the different options available!

Regards

**Comment by PhillipHamlyn** [comment]
Sounds great - I'll use the override extension methodology.
