### ISSUE TITLE
Pre-defined Site Map ?

### ISSUE THREAD

**Issue by PhillipHamlyn** [PiranhaCMS/Piranha#486]
Hi,

I can see I can have predefined page types etc. Is it possible to pre-define a Site Map to prevent me having to manually use the Manager to describe my pre-existing site ? (I am adding Piranha to an existing MVC site).

**Comment by tidyui** [comment]
Hi there! There's currently no data-import available in Piranha. Page & Post types can be imported from code as they are regarded meta-data.

Regards
