### ISSUE TITLE
Removing sitemap.xml handler

### ISSUE THREAD

**Issue by HeyJoel** [PiranhaCMS/Piranha#492]
Hi there, i'm loving the idea behind the CMS not getting in your way, but unfortunately i'm having issues with disabling the sitemap.xml handler. 

I already have a dynamic sitemap handler in my site which serves up all my custom routes, so I don't want the piranha one which only shows my blog content. Is there a way to disable it? I'm already running in passive mode which I thought would do the trick. I've tried removing the handler reference from the web.config too.

**Comment by tidyui** [comment]
Hi there! If I remember correctly the site map is added as a handler in web.config! Remove the lines for the handler and it should be inactivated!

**Comment by HeyJoel** [comment]
I've tried that one! I found an issue (#303) in which you mention that it's not actually an http handler which references this code:

https://github.com/PiranhaCMS/Piranha/blob/2.2.4/Piranha/Application.cs#L161

But that's as far as I've dug down so far. Is there any mechanism for overriding this config?

**Comment by tidyui** [comment]
Ah, sorry I thought you had removed the handler, sometimes the web.config setup can interfer even after this is done. Take a look at section 3 on this page for how to remove a handler!

http://piranhacms.org/docs/api-reference/routing

**Comment by HeyJoel** [comment]
Excellent, somehow I must have missed that in the docs. Awesome work on the cms and thanks for the help!
