### ISSUE TITLE
A region with post models does not contain categories

### ISSUE THREAD

**Issue by ugniuslt** [PiranhaCMS/Piranha#495]
Hi,
there are two types of regions to display posts on a page: posts and post models.
I get the page model by calling Piranha.Models.PageModel.GetByPermalink("foo");
If I use a posts region on the page, the posts do not contain property information.
If I use a post models region, the models contain properties, but do not contain categories even though they are assigned to posts. Is there a way to retrieve both properties and categories without having additional roundtrips into the DB for each post (the page might contain dozens of them).

Thanks,
Ugnius

**Comment by tidyui** [comment]
I'll take a look at this. If the categories are in fact omitted from the model it is a bug!

**Comment by ugniuslt** [comment]
It turned out that not only Categories, but also the Permalink was not included.
I fixed that locally by modifying this method in Piranha.Entities.PostModel:
```
    public static IList<PostModel> Where(Expression<Func<Post, bool>> predicate) {
			var ret = new List<PostModel>();

			using (var db = new DataContext()) {
				var posts = db.Posts
					.Include(p => p.Template)
					.Include(p => p.Properties)
					.Include(p => p.Extensions)
                    .Include(p => p.Categories) //add this
                    .Include(p => p.Permalink) //add this
					.Where(predicate)
					.ToList();

				foreach (var post in posts)
					ret.Add(BuildModel(db, post));
			}
			return ret;
		}
```
