### ISSUE TITLE
Prefix turned off, yet want prefix on Post controller

### ISSUE THREAD

**Issue by cvillard** [PiranhaCMS/Piranha#496]
Hello,

First off thanks for the system, I am really digging it so far! I have turned of prefixing because I did not want home/ on each url. However I DO want to use a custom prefix on posts, so the URL hierarchy will look like all my posts live under /blog/.

I have tried using a custom route mapping in the route config, but I have not been able to get it to work. So in essence, I would like my url to be /blog/(permalink)

I searched around but I did not find something that was exactly like what I am looking for.

Thanks
Charlie

**Comment by tidyui** [comment]
There's currently no build in support for this, although it's probably something that can be implemented in your project either using one of the system hooks or by rewriting all requests to `/blog` in your begin request.

**Comment by negrond** [comment]
My work around for the mean time is to make sure to prepend the Post Permalink with **blog/** which yields the desired outcome. Maybe a possible solution would be to add a setting which allows for an optional Post Permalink Prefix value.

**Comment by tidyui** [comment]
Absolutely. You could actually make this kind of behavior automatic by handling it in the manager **hook** for when a post is saved from the manager interface. 

    Hooks.Manager. PostEditModelBeforeSave += (model) => {
      if (!model.Permalink.Name.StartsWith("blog/") {
        model.Permalink.Name = "blog/" + model.Permalink.Name;
      }
    };

Regards
