### ISSUE TITLE
tinymce table support

### ISSUE THREAD

**Issue by CentricStraaten** [PiranhaCMS/Piranha#497]
I tried to enable table support for the tinymce editor. When i add the table plugin an error occurs. 

Configuration
`tinymce.init({
        mode: "specific_textareas",
        editor_selector: "editor",
        convert_urls: false,
        plugins: [
            "autoresize autolink code hr paste piranhaimage link table"
        ],
        width: "100%",
        height: "340",
        autoresize_min_height: 340,
        toolbar: "bold italic underline | bullist numlist hr  | formatselect removeformat | cut copy paste | link piranhaimage | code ",
        @if (File.Exists(Server.MapPath("~/areas/manager/content/css/editor.css"))) {
            <text>content_css: "@Url.Content("~/areas/manager/content/css/editor.css")",</text>
        }
    });`

Console message
`http://staging.fiducia.nu/res.ashx/areas/manager/content/js/ext/tiny_mce/plugins/table/plugin.min.js`

Failed to load: `http://staging.fiducia.nu/res.ashx/areas/manager/content/js/ext/tiny_mce/plugins/table/plugin.min.js`

Adding the plugin script which failed to load does not solve the problem.

I als tested other plugins (for example: colorpicker) with the same result.

How do i enable table suppport?

**Comment by tidyui** [comment]
Hi there! I don't think the current version includes the complete TinyMCE package, it's also an older version of TinyMCE:

https://github.com/PiranhaCMS/Piranha/tree/2.2.5/Core/Piranha/Areas/Manager/Content/Js/Ext/tiny_mce/plugins

However, the latest beta available on Nuget has the complete TinyMCE package of version 4.3.1:

https://github.com/PiranhaCMS/Piranha/tree/master/Core/Piranha/Areas/Manager/Content/Js/Ext/tiny_mce/plugins

You can use the latest beta by upgrading using `-pre`.

    Install-Package PiranhaCMSMvc -Pre

or

    Install-Package PiranhaCMS -Pre

Depending on you run MVC or WebPages

**Comment by samuelmaxton** [comment]
Greetings, 

How can I change the default initialization in the tinymce content editor without upgrading the entire CMS to beta? I would like to use left/right/center alignments.

Thanks

**Comment by tidyui** [comment]
See the answer to #501 

Regards

**Comment by tidyui** [comment]
Next version will include the complete TinyMCE package
