### ISSUE TITLE
Timeout expired

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/Piranha#498]
Two out of three sites I just migrated to Godaddy are give me this error when I try to publish larger pages.

> System.Data.SqlClient.SqlException (0x80131904): Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteScalar() at Piranha.Data.ActiveRecord`1.GetScalar(String statement, Object[] args) at Piranha.Models.Manager.PageModels.EditModel.<>c__DisplayClassa.<SaveAll>b__4(Region r) at System.Collections.Generic.List`1.ForEach(Action`1 action) at Piranha.Models.Manager.PageModels.EditModel.SaveAll(Boolean draft) at Piranha.Areas.Manager.Controllers.PageController.Edit(Boolean draft, EditModel pm) ClientConnectionId:ec2d4980-935e-47e4-8cf9-ab006f50bcb7 Error Number:-2,State:0,Class:11

I saw #370 but all three connection strings have `MultipleActiveResultSets=True`

**Comment by tidyui** [comment]
If you've migrated the database between different servers, make sure that all primary keys & indexes are intact. I have seen some cases where some migrations tool have restored the database without any keys & constraints which has caused these kinds of timeout errors when publishing pages as its a transaction based operation.

Best regards

Håkan

**Comment by Eonasdan** [comment]
You're probably right. Scripts + Data Export is the worst way to do migrations *sigh*. Let me check this out and get back to you

**Comment by Eonasdan** [comment]
Yup that was it. Thanks

**Comment by eswarg02** [comment]
Thanks Dude Its Working Fine.
