### ISSUE TITLE
Editing TinyMCE Initialization to Customize Toolbar

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#501]
This is the current initialization (below). I would like to customize the editor's toolbar to include left/right/center alignments. If I could only access this source code directly?? Help!

    `tinymce.init({
        mode: 'specific_textareas',
        editor_selector: "editor",
        convert_urls: false,
        plugins: [
            "autoresize autolink code hr paste piranhaimage link"
        ],
        width: "100%",
        height: "340",
        autoresize_min_height: 340,
        content_css: "/areas/manager/content/css/editor.css",
        toolbar: "bold italic underline | bullist numlist hr | formatselect removeformat | cut copy paste | link piranhaimage | code",
    });`

**Comment by tidyui** [comment]
All views can be overriden by placing them at the same location in your project. You can take a look at this blog post, but use the current view in the repo as template:

http://piranhacms.org/customizing-the-html-editor

The source view can be found at:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml

**Comment by samuelmaxton** [comment]
Thanks! I did not realize I could override. Much appreciated!
