### ISSUE TITLE
Which Type(.png,.jpg) of Image is best for fast reterieval?

### ISSUE THREAD

**Issue by eswarg02** [PiranhaCMS/Piranha#503]

**Comment by tidyui** [comment]
The best way for fast retrieval is to use images of adequate size on the pages. Uploaded images can easily be scaled, resized & cropped when referenced using the `UI` helper.

http://piranhacms.org/docs/api-reference/ui-helper

**Comment by eswarg02** [comment]
Thanks Dude.
Want to show the gallery Image as pop up while click on it is it possible in CMS ?

**Comment by tidyui** [comment]
Not sure what you mean. Piranha CMS doesn't include any view for the client web application, it's just a content management tool. If you want a gallery you in your site you have to build it or use an external component.

Regards
