### ISSUE TITLE
Question - Page Type Advanced Settings and Mixed Controller Syntax

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#505]
Greetings, I have a couple questions:

**Page Type Advanced Settings**
"Route" - Should I put a custom controller name here? I see that the default is "Page" so I imagine that is referencing the Page Controller. 
"View" - I don't understand why this field is in the Edit Page Type manager page. Doesn't this mean that I cannot have more than one Page for a given Page Type, because a Page Type only has ONE View?? In MVC I am used to having multiple Views all in the same controller, each View with its own unique Model.

I also don't understand how a **page can change a route or a view**? What is an example of this?

**Mixed Model Example**
`public ActionResult Index()
        {
			var model = new Models.MixedModel() { 
				Now = DateTime.Now,
				CMSData = this.GetModel("mixed")
			};
			return View(model);
        }`

In the example above I am not understanding the syntax using the string "mixed" as an argument in the GetModel method:
`CMSData = this.GetModel("mixed")`
What is this doing?

Thanks for your help!
Sam Thompson
sthompson@blusolutions.biz

**Comment by tidyui** [comment]
##Route

The *Route* is the underlying route you want requests for this permalink to be sent. It can be a combination of controller & action. For example if you enter the route `~/home/about` and you have a `HomeController` with an action named `About` this action will handle the request for this page type.

## View

In some cases you want the same route (business logic) to handle multiple pages but present them in different ways. Using the view field you can add information about which view should be used which can then be used in the controller action when called the `View` method.

## Change route of view

Piranha CMS is very simple. When a request comes in the available permalinks are searched, if a match is found the `route` from the page type (or the page if it overrides it) is fetched and the request is then *rewritten* to that route. In other words, all requests are just handled by plain old MVC controllers, the permalinks are used as a mapping.

## Mixed mode

Well the example probably just loads a fixed page from the database, namely one with the permalink named "mixed".

**Comment by samuelmaxton** [comment]
Thank you!
