### ISSUE TITLE
"My Site" URL Issue

### ISSUE THREAD

**Issue by thirdvalve** [PiranhaCMS/Piranha#508]
How does one change the protocol, host and request URI that is used for "My Site"?

We have a problem in that this shows up as "http://oursitedomain.com:8454", which is fine in our local development environment.  In our shared DEV environment, the protocol needs to be HTTPS, and for some odd reason, the port gets in the way, such that preview pages cannot be displayed.   If one manually changes the protocol to HTTPS and removes the port, the preview works.

How can we modify this base URL so that it would read "https://oursitedomain.com" (with no port)?

Is this done is a configuration file somewhere?  Do we need to modify code to change the way the URL is generated?
- Dave

**Comment by tidyui** [comment]
The preview URL is generated based on the URL you're currently accessing the site on. If you were to log into the manager with `https://oursitedomain.com` the preview URL should be based on that.

Regards
