### ISSUE TITLE
Extension Exception

### ISSUE THREAD

**Issue by CentricStraaten** [PiranhaCMS/Piranha#511]
Hi,

I created an extension for a post.

`using System;
using System.ComponentModel.Composition;
using Piranha.Extend;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

[Export(typeof(IExtension))]
[ExportMetadata("InternalId", "Calender")]
[ExportMetadata("Name", "Agenda")]
[ExportMetadata("Type", ExtensionType.Post)]
[Serializable]
public class CalendarExtension : Extension
{
    [DisplayName("Datum")]
    [DataType(DataType.Date)]
    [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
    public DateTime StartDate { get; set; }

    [DisplayName("Tijd")]
    [DataType(DataType.Time)]
    [DisplayFormat(DataFormatString = "{0:HH:mm}", ApplyFormatInEditMode = true)]
    public TimeSpan Time { get; set; }

    [DisplayName("Locatie")]
    public string Location { get; set; }
}`

In my application i include the extension in my linq query.

`                    calendarItems = db.Posts.Where(p => p.Template.Name == "Agenda")
                    .Include(x => x.CreatedBy)
                    .Include(x => x.Extensions)
                    .ToList();`

When i step through my application i can verify in my view that the exentsion is retrieved from the database.

`@model Bengkel.Fiducia._2016.Models.CalendarViewModel
@{
    ViewBag.Title = Model.Page.Title;
}

@if (@Model.CalendarItems.Count == 0)
{
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-warning" role="alert">Er is geen agenda beschikbaar.</div>
        </div>
    </div>
}
else {
    foreach (var calendarItem in @Model.CalendarItems)
    {
        //var item = calendarItem.Extensions.ByInternalId("CalendarExtension").GetBody<CalendarExtension>();

    }
}`

My view however throws a "Object reference not set to an instance of an object." as soon as i enable the code:

`/var item = calendarItem.Extensions.ByInternalId("CalendarExtension").GetBody<CalendarExtension>();`

Can anyone help me solve this problem?

**Comment by tidyui** [comment]
By looking at your code it appears that the **InternalId** is `Calendar` and not `CalendarExtension`.

    var item = calendarItem.Extensions.ByInternalId("Calendar").GetBody<CalendarExtension>();

**Comment by CentricStraaten** [comment]
I als tried Calendar" as internal Id. I received the same exception.

**Comment by CentricStraaten** [comment]
This code solved the problem. Seems like ByInternalId is not working correctly?

`var item= calendarItem.Extensions.FirstOrDefault(e => e.Type == "CalendarExtension").GetBody<CalendarExtension>();`
