### ISSUE TITLE
Extension DateTime Issue

### ISSUE THREAD

**Issue by CentricStraaten** [PiranhaCMS/Piranha#512]
I have created an extension. The extension has a DateTime property. Whenever i enter a date in the manager, it saves the previous day? For example i enter: december 12 2016 it will save december 11 2016!

TimeSpan is saved but can not be retrieved from database. It always returns 00:00:00.

**Comment by CentricStraaten** [comment]
Is there any progress on this issue?

**Comment by lfontaine974** [comment]
In your model extension, you can do that
`
public override void OnManagerSave(object model)
    {
        this.Date_Debut_MiseEnLigne = this.Date_Debut_MiseEnLigne**.ToLocalTime()**;
        this.Date_Fin_MiseEnLigne = this.Date_Fin_MiseEnLigne**.ToLocalTime()**;
    }
`
