### ISSUE TITLE
Question: How to make an AJAX call to a Controller Method from a Piranha Page?

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#513]
Greetings,

ASP.NET MVC

I am attempting to make an ajax call to a custom method in my controller from a Piranha page. I believe the problem is related to routing (?) but not sure how to overcome. 

**EDIT** 

I am able to reach the controller method by entering the FULL URL path:
`$.ajax({
        url: 'http://localhost:56876/Location/GetLocationPartial',`
    
Entering a shorter URL without the domain name causes the error:
`$.ajax({
        url: '/Location/GetLocationPartial',
`

**However, this is not ideal! What am I missing???**

**EDIT**

I believe I understand. My Location Controller inherits from SinglePageController.  If I instead make a call to a method in a controller that inherits directly from the "Controller" base class, everything appears to work.

**Comment by PZapleshnikov** [comment]
You can use **UI.Permalink()**

**Example:**
`        $.ajax({
            url: '@UI.Permalink()/someaction',
            type: "POST",
            success: function (data) {
                console.log(data);
            }
        })`

**Comment by samuelmaxton** [comment]
Thanks! This works.

**Comment by tidyui** [comment]
Good answer @PZapleshnikov! Yes the SinglePageController expects the request to have been rewritten by the Piranha routing and tries to read the permalink from the HttpRequest, accessing it directly probably doesn't work.

The good thing with @PZapleshnikov answer is of course also that you can have a single post action in your controller but handle things slightly different in it depending on which page instance in the Sitemap you have posted to!
