### ISSUE TITLE
Question - How to retrieve current User object and check for Group?

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#515]
Greetings,

In your documentation, under the heading "Entities", you list both the **User** and **Group** classes. And you say, 

_"Groups are used throughout the manager interface and can be used in the applications to control access to controller actions, form actions and as conditionals in the .cshtml templates_."

I would very much like to use Group as conditionals in my view and as a way to control access in my controllers, but I am not understanding how this is done. Is there an example of this available? I'm just not sure how to access the current user object??

Thanks!
Sam T

**Comment by samuelmaxton** [comment]
I found some ideas in your source code:

`bool access = User.HasAccess("ADMIN_ACCESS"))`

`Piranha.Models.SysUser usr = (Piranha.Models.SysUser)(HttpContext.Session[PiranhaApp.USER]);`

 Is there better ways?

**Comment by tidyui** [comment]
The manager interface uses the first approach to check for permissions. You can take a look at the code here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Views/Page/Edit.cshtml#L112

Regards

Håkan
