### ISSUE TITLE
Question - Overwriting Menu.cshtml Not Working

### ISSUE THREAD

**Issue by samuelmaxton** [PiranhaCMS/Piranha#516]
Greetings,

I am trying to overwrite the Menu.cshtml file by adding a new partial view to the following path: (Areas\Manager\Views\Shared\Partial\Menu.cshtml). I am trying to better control the styles of the menu and add dropdown menu functionality. However, after adding this partial view, I am still getting the old code and it is not being overwritten. Is there a reason for this? Am I missing something?

Thanks!
Sam T

**Comment by Lucstar** [comment]
Hey Samuel, I don't know regarding replacing Menu.cshtml. I use Hooks instead. 

Here is my example of a bootrap menu, check www.ostgotamarknader.se for an example.

Ref: https://piranhacms.org/docs/api-reference/hooks

_AppStart.cshtml
`@{


    Piranha.WebPages.Hooks.Menu.RenderLevelStart = (ui, str, css) =>
    {
        if (str.Length == 0 || (css == "list-group") || (str.ToString().IndexOf("list-group") > 0))
        {
            if ((str.ToString().IndexOf("list-group") > 0) && css=="")
                css = "list-group";
            str.AppendFormat("<ul class='{0}'>", css);
        }
        else
        str.Append("<ul class='dropdown-menu' role='menu'>");
    };

    Piranha.WebPages.Hooks.Menu.RenderItemStart = (ui, str, page, active, activechild) =>
    {
        if (page.Pages.Count > 0)
        {

            if (str.ToString().IndexOf("list-group") > 0){
                str.Append("<li class='" + (active || activechild ? "active" : "") + " list-group-item'>");
                str.Append(String.Format("<a href='{0}'>{1} <span class='caret'></span></a>", ui.Permalink(page.Permalink), page.NavigationTitle ?? page.Title));
      
            }
            else {
                str.Append("<li class='dropdown " + (active || activechild ? "active" : "") + "'>");

                str.Append(String.Format("<a href='{0}' class='dropdown-toggle' data-toggle=''>{1} <span class='caret'></span></a>", ui.Permalink(page.Permalink), page.NavigationTitle ?? page.Title));
        }}
        else
        {
            if (str.ToString().IndexOf("list-group") > 0)
                str.Append("<li class='" + (active || activechild ? "active" : "") + " list-group-item'>");
            else    
                str.Append("<li class='" + (active || activechild ? "active" : "") + "'>");
            str.Append(String.Format("<a href=\"{0}\">{1}</a>", ui.Permalink(page.Permalink), page.NavigationTitle ?? page.Title));
   
        }
    }; 
}`

**Comment by tidyui** [comment]
Hi there!

The RazorGenerated views are set to **allow physical files if newer**, which means your local files should override the ones included in the dll if they are newer.

Regards

Håkan
