### ISSUE TITLE
Template Overriding not working in Visual Studio 2015

### ISSUE THREAD

**Issue by bluisana** [PiranhaCMS/Piranha#521]
Hello, 

I first want to say that I love piranha.  I have been using different flavors of CMS as well as our homegrown one for over 10 years now and this is by far the most developer friend CMS I have ever seen.  

For some reason that I can't figure out why the Manager/Area/Views in my project won't override the default templates.  I am specifically trying to override the Areas\Manager\Views\Shared\Partial\TinyMCE.cshtml template but it just doesn't override at all.  I tried several other templates as a test and non of them seem to work.   I can't find any errors on build that lead me to what may be going on.   How can I troubleshoot this? 

Thanks for your time,

**Comment by bluisana** [comment]
I believe this was happening because I am compiling Piranha core in my solution as a separate project and then using the dll output as a reference.  This is causing the pirahna dll to always have a greater date the last change date of my views in my cms project.  

To fix this I just changed RazorGeneratormvcstart.cs file to always overwrite files with local ones like below. 

This may be a reasonable change to add to the code set as I can't see why you wouldn't want to always overwrite any files you create locally.  If you didn't want those files to overwrite the default compiled views then you wouldn't create them.  

public static void Start() {
            var engine = new PrecompiledMvcEngine(typeof(RazorGeneratorMvcStart).Assembly) {
                
                UsePhysicalViewsIfNewer = HttpContext.Current.Request.IsLocal
            };

            ViewEngines.Engines.Add(engine);

            //Changed to always allow local views to override compiled views
            //ViewEngines.Engines.Insert(0, engine);

            // StartPage lookups are done by WebPages. 
            VirtualPathFactoryManager.RegisterVirtualPathFactory(engine);
        }

**Comment by tidyui** [comment]
Hi there! 

Thanks for your kind words, always fun to hear when people find your work useful and helpful :) Even though it's quite early, please check out the upcoming, completely re-written version for dotnet core available here (https://github.com/piranhacms/piranha.core). It's always useful to get comments and feedback from users early on in the process.

Regarding your question you're absolutely right, when including the source code into the build the embedded views will give you some trouble, but your solution is solid. I'm actually not sure **why** the view engine is inserted at the first position in the first place, I think it's a remained of the template code that comes with the RazorGenerator.Mvc package :)

Regards

Håkan

**Comment by bluisana** [comment]
Hey Hakan,

I am planning to use Pirhana for some upcoming projects which are going to require moving some functionality from our web forms based CMS into Pirahna.  If all works out I would be glad to contribute the functionality.  The main things will be bulk emailing of users and AD integration.

Bryan Luisana
President/Systems Architect
Cell: 919-291-0968<tel:919-291-0968>
[http://www.blusolutions.biz/email%20sig/image001.gif]

**Comment by tidyui** [comment]
Hi again, I checked out the code that registers the manager area, and in my opinion it already registers the Precompiled view engine **after** the basic razorviewengine, or am I wrong?

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Manager/ManagerModule.cs#L46

**Comment by bluisana** [comment]
Hey Hakan,

I haven’t looked at this in quite a while but I know that I was unable to make template view changes in my scenario with the default Pirahna configurations.


I probably have a different setup from most users though.  I had the piranha source code in my project along with my CMS project using the compiled piranha dlls.  I included the output of the piranha source project as a reference in my CMS project.  When you are setup like that it definitely didn’t let me overwrite views without changing some settings in the RazorGeneratorMvcStart
Class.

I hope all is going well with Pirhana and please don’t give up on it.  You are really the only game in town with a developer friendly CMS that can easily be plugged into existing projects.

Bryan Luisana
President/Systems Architect
Cell: 919-291-0968<tel:919-291-0968>
[http://www.blusolutions.biz/email%20sig/image001.gif]
