### ISSUE TITLE
Event onclick is not saving in HTML regions

### ISSUE THREAD

**Issue by afernandezd** [PiranhaCMS/Piranha#523]
Hi. The error I've seen is that the CMS is not showing the onclick events in an HTML region. I'm saving that HTML directly to the database, when I'm going to edit it on the CMS, the onclick event are not being retrieved, when save changes obviously the onclick event is lost.

**Comment by tidyui** [comment]
I'm not following 100%. If you are meaning that the HTML-editor removes `onClick` javascript events you've pasted into the editor that might be true as the TinyMCE by default "cleans" the given input before loading & saving it.

If you need to add this kind of stuff in the editor you can customize the editor setup in your installation, take a look here:

http://piranhacms.org/customizing-the-html-editor

The blog post is for the **old** version of the editor, so you need to get the newest setup from the repo here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml

but apart from that it still applies.

To see how you can customize the editor, please go to the official homepage of TinyMCE:

https://www.tinymce.com/

Regards
