### ISSUE TITLE
Upgrade to current .NET version and others....

### ISSUE THREAD

**Issue by natiki** [PiranhaCMS/Piranha#524]
Hi,

- This is partially related to: https://github.com/PiranhaCMS/piranha.core/issues/34

Could we target current versions of things such as:

- .NET 4.61
- AutoMapper 5.2.x

I am trying to make use of the EF models provided by PiranhaCMS.Core and am running into dependency hell as the rest of our solution is a couple of years a head in versions for the above.

**Comment by tidyui** [comment]
Hi! I don't see any issue in upgrading the master branch to the latest version of everything. I just need a little time to fix the NuGet-packages!

Regards

**Comment by natiki** [comment]
Sounds good.

**Comment by tidyui** [comment]
I will update the NuGet-packages, however I don't see any reason for updating .NET to 4.6.x as it's not needed. I also just tried creating a web project with 4.6.1 and include the NuGet-package and I'm not getting any errors, did you manage to resolve yours?
