### ISSUE TITLE
Question : Where are stored the medias ?

### ISSUE THREAD

**Issue by Robouste** [PiranhaCMS/Piranha#525]
Hi, 

I have to work on a project build with Piranha and I'm a bit lost. On production, medias are not working. It generates a link like "/media/guid" but it falls back on a not found page. 

It works in development (localhost) and I really don't understand why. It's probably a problem within our project but maybe you could guide me. **Where are those medias ? How can I debug the path ? How does it works ?** I have no "media" folder in the solution.

I'm sorry for asking but I'm not very familiar with all the ASP.Net thing so I'm a bit lost. Any help is appreciated.

Thanks !

**Comment by tidyui** [comment]
Hi there!

All media are stored in the `App_Data\Content` directory. If the links doesn't work in production my guess is that `App_Data` is excluded when publishing the application.

Regards

Håkan

**Comment by Robouste** [comment]
The checkbox "Exclude files from the App_Data folder" is not checked.
Could it be a permission problem ? The folder is empty on the folder (juste a index.html file) and I've uploaded some pdf via the manager.

**Comment by tidyui** [comment]
It could be, but you wrote that it works in development. If you check the same folder in your development environment the files should be present there.

**Comment by Robouste** [comment]
Thanks for your help, I found a backup with all medias so I put it back on production server. Now it works.

Have a nice day

**Comment by tidyui** [comment]
Great! Make sure you don't have `Delete all files before publish` checked since this will indeed delete all uploaded media before you publish to production.

**Comment by Robouste** [comment]
"Delete all files before publish"

I feel so dumb now... thank you
