### ISSUE TITLE
Revision History

### ISSUE THREAD

**Issue by drosenba** [PiranhaCMS/Piranha#527]
There was some discussion here about Revision History feature
[https://github.com/PiranhaCMS/Piranha/issues/206](https://github.com/PiranhaCMS/Piranha/issues/206)

However, it's 3 years old.  Has there been any additional consideration/work done in that area?

**Comment by tidyui** [comment]
Hi there! I'd say revision history is out of scope for the current version of Piranha CMS, or there haven't at least been any plans on implementing this feature.

Regards
