### ISSUE TITLE
Invalid column name 'content_reference'

### ISSUE THREAD

**Issue by microelectro** [PiranhaCMS/Piranha#531]
Hi. in version 2.2.6 when click on "Images & documents" in "CONTENT" page and click "Add new -> Standard post" in "Post" page the error page coming!

error :

Server Error in '/' Application.
Invalid column name 'content_reference'.
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'content_reference'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.
![imageerror](https://cloud.githubusercontent.com/assets/10531380/22172723/d84ad08a-dfc3-11e6-947d-9f6ec31f74ad.png)

**Comment by duanenewman** [comment]
Same error. For some reason the column does not exist. I see where it should be inserted with script 35.sql (it is worth noting that I did have [post_excerpt] from 36.sql). Strange that it skipped 35, or it somehow failed. I just found the DB update code and am looking for a reason that it might not run 35, or somehow skip over it.

a workaround is to manually run the contents of 35.sql in your database to add the column:

ALTER TABLE [content] ADD [content_reference] BIT NOT NULL default(0);

**Comment by tidyui** [comment]
I just uploaded service release 2.2.6.1 to NuGet. The error was that the new column from `35.sql` was not included in the initial create script. This meant that updating an existing database would be successful, but creating a new from scratch would result in the error you submitted.

2.2.6.1 amends this and includes the column in the create script.

**Comment by JosueMartinez** [comment]
there is no version 2.2.6.1
