### ISSUE TITLE
Unable to Install Package PiranhaCMS.Mvc

### ISSUE THREAD

**Issue by jmojiwat** [PiranhaCMS/Piranha#535]
Hi Håkan,

PiranhaCMS looks amazing and I think would help meet our needs for our site. We want to integrate PiranhaCMS into our existing site. 

Unfortunately I'm having trouble installing. When I tried: Install-Package PiranhaCMS.Mvc

I got the "Failed to add reference. The package 'PiranhaCMS.Core' tried to add a framework reference to 'System.Linq' which was not found in the GAC. This is possibly a bug in the package. Please contact the 
package owners for assistance." error.

I tried version 2.2.5 too but got the same error.

Any clues?

Jake

**Comment by tidyui** [comment]
Since Piranha CMS is compiled for (and thus compatible with) .NET 4.0 it references System.Linq from the GAC for that version. My guess is you have a new development machine and only have the latest .NET libraries installed?

Regards

**Comment by jmojiwat** [comment]
Yes you're right. We are also now compiling on .NET 4.6. Would we still be able to use PiranhaCMS?

**Comment by tidyui** [comment]
As to my knowledge .NET 4.6 should be backwards compatible with 4.0! If you have any issues let me know!

**Comment by jmojiwat** [comment]
Great! Any recommendations how to get around the error message? After I get the error message, the installation will roll back so our install was unsuccessful. :(

**Comment by tidyui** [comment]
Making sure you have .NET 4.0 installed on your dev machine should do the trick!

**Comment by jmojiwat** [comment]
I tried to install .NET 4.0 but it won't install because the installer says it is already part of the operating system.

On a new ASP.Net MVC project, I was able to install PiranhaCMSMvc.

I wanted to install Piranha on an existing website. What is the difference between PiranhaCMSMvc and PiranhaCMS.Mvc nuget packages? Can I install PiranhaCMSMvc on an existing website instead? (The documentation http://piranhacms.org/docs/introduction/getting-started says to use PiranhaCMS.Mvc for an existing website but I can't get it to work)

**Comment by jmojiwat** [comment]
Hi @tidyui, I think I found the source of the problem.

If I installed PiranhaCMS.MVC from a clean ASP.Net MVC Project, it would work.

However if I install System.Net.Http (https://www.nuget.org/packages/System.Net.Http) first, then installing PiranhaCMS.Mvc will fail.

**Comment by tidyui** [comment]
Ok, it has to be some kind of version issue with the System.Net.Http package. How unkind of VS not to give any notification about it when installing the Piranha package :)
