### ISSUE TITLE
Hi, i get this error clicking Images & documents

### ISSUE THREAD

**Issue by EBBN9018** [PiranhaCMS/Piranha#537]
I can log in, and click on the tabs for pages, post, and comments. The problem is when i click on Images & documents, it sends me to this error page. Any help would be appreciated, thank you.

![screen shot 2017-02-02 at 4 56 05 pm](https://cloud.githubusercontent.com/assets/8870674/22570307/ca79ea46-e968-11e6-8a81-e3e5c5a7a699.png)

**Comment by tidyui** [comment]
Hi there! Did you do a fresh install or update?

Regards

**Comment by EBBN9018** [comment]
I did a fresh install.

**Comment by tidyui** [comment]
You were completely right! Those fields that were added in the latest release (2.2.7) were missing from the Create script, so the it only worked with an update of an existing installation. There's a new version of `Piranha.Core` (2.2.7.2) available on NuGet!
