### ISSUE TITLE
ManagerModule Error

### ISSUE THREAD

**Issue by munvee** [PiranhaCMS/Piranha#539]
**Help,I am trying to deploying piranha site to windows 2008 running IIS7 ..I am getting error which is related to ManagerModule.cs, The stack trace is as follows:**

[ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) +0
   System.Reflection.RuntimeModule.GetTypes() +9
   System.Reflection.Assembly.GetTypes() +143
   RazorGenerator.Mvc.PrecompiledMvcEngine..ctor(Assembly assembly, String baseVirtualPath, IViewPageActivator viewPageActivator) +819
   Piranha.Manager.ManagerModule.Init() in C:\Case Management\IntegratedCaseManagement\ICMS\Core\Piranha\Manager\ManagerModule.cs:39

[TargetInvocationException: Exception has been thrown by the target of an invocation.]
   System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
   System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +229
   System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +211
   System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) +35
   WebActivatorEx.ActivationManager.RunActivationMethods(Boolean designerMode) +684
   WebActivatorEx.ActivationManager.Run() +129

[InvalidOperationException: The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.Compilation.BuildManager.InvokePreStartInitMethodsCore(ICollection`1 methods, Func`1 setHostingEnvironmentCultures) +989
   System.Web.Compilation.BuildManager.InvokePreStartInitMethods(ICollection`1 methods) +199
   System.Web.Compilation.BuildManager.CallPreStartInitMethods(String preStartInitListPath, Boolean& isRefAssemblyLoaded) +272
   System.Web.Compilation.BuildManager.ExecutePreAppStart() +171
   System.Web.Hosting.HostingEnvironment.Initialize(ApplicationManager appManager, IApplicationHost appHost, IConfigMapPathFactory configMapPathFactory, HostingEnvironmentParameters hostingParameters, PolicyLevel policyLevel, Exception appDomainCreationException) +1037

[HttpException (0x80004005): The pre-application start initialization method Run on type WebActivatorEx.ActivationManager threw an exception with the following error message: Exception has been thrown by the target of an invocation..]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +646
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +159
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +778

**Comment by tidyui** [comment]
From the stacktrace we can see that the error occurs on line 39 in `ManagerModule`.

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Manager/ManagerModule.cs#L39

Looking at the code I am assuming that you have deployed the project without including `RazorGenerator.Mvc.dll`. This file is included in the NuGet-package `Piranha.Core` and you probably have it on your development machine.

Regards

**Comment by munvee** [comment]
Thank you so much..that resolved the problem!Good Product you have there!
