### ISSUE TITLE
Sitemap not showing pages as https

### ISSUE THREAD

**Issue by matt-ville** [PiranhaCMS/Piranha#541]
Hi,

We're using Piranha 2.2.5 with a MVC 5 project. Our whole site runs under https, but we've just noticed that the generated sitemap.xml list's every page as http, and think this is causing problems with google indexing the pages. I've look at what i can, but wanted to check if there are an config options to change this, so urls in the sitemap appear as https.

Thanks!

Matt

**Comment by tidyui** [comment]
When I look at the code it looks like the sitemap handler will generate links on the same scheme as it was accessed. So if you call sitemap.xml on `https` the links should be generated for HTTPS. Can you check if this is the case or if there's something else wrong.

Regards

**Comment by matt-ville** [comment]
Thanks for getting back to me Håkan

I did notice this in the code too, but it's definitely being called from https, an example https://www.stepjockey.com/sitemap.xml

So i think it may be something else, but i'm not sure where to look next.

Thanks!

Matt

**Comment by matt-ville** [comment]
@tidyui sorry to ask again, but did you have any other thoughts on this? No worries if not, i'll take a closer look.

**Comment by tidyui** [comment]
Sorry I've been extremely busy at work and haven't had the time to investigate further. My suggestion is that you take the file for the sitmap handler (which is just registered in web.config), copy to your own project, change namespace and register your version instead. This way you can see what happens and tweak it for your needs! You can find the file here:

https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Web/Handlers/SitemapHandler.cs

Regards
