### ISSUE TITLE
How do I make MySql work with EF in Piranha?

### ISSUE THREAD

**Issue by Rathje** [PiranhaCMS/Piranha#542]
Hi,
First of all thanks for a great product. I have a previous version installed fine with MySQL. But recently I installed another and newer version, where it seems to not be able to use MySQL. I have set up provider exactly as the old one using entity framework, but still it breaks with error during create process.
Would this be solved if I could use an initial schema of some sort? And where do I find one? Or can I copy my current database and adapt it? Which basic records should be in place?
I know - many questions - but perhaps someone can lead me in a direction, please.. :)
Best regards
Lars

**Comment by tidyui** [comment]
See my response on issue #455!
