### ISSUE TITLE
Html.Partial("Partial/Tabs") not rendered in custom entity edit view

### ISSUE THREAD

**Issue by KamalRanaweera** [PiranhaCMS/Piranha#543]
I am creating a custom entity called Collection and when I go to manager/collection/edit page, the tabs are not displayed. However these tabs are correctly displayed in the manager/collection list view. I'm using ADMIN_CONTENT access in both list and edit methods of the controller of my custom entity.

**Comment by tidyui** [comment]
Great! You can simplify it by actually just removing `SelectedActions`. If you leave it blank *ALL* actions in the specified controller are accepted. SelectedActions is really only needed if different actions in the same controller should trigger different menu items!

Regards
