### ISSUE TITLE
Stop New Site Creation

### ISSUE THREAD

**Issue by glerler** [PiranhaCMS/Piranha#544]
I have migrated a solution built on Piranha CMS to a new VS install.  Now when I start it up it kicks me over to the install a new site in management area.   I remember this being an issue with not seeing the existing db.  I know my db path and credentials are correct.  I updated the connection string.  What am I wrong on?? Is there something else that will cause this scenario??  Is there another path issue???  Cant seem to find any documentation for this.  Thx

**Comment by tidyui** [comment]
Hmm, haven't seen this before, the only problems I'm aware of from earlier issues is that Entity Framework has tried to create the database when it should in fact be created by the internal SQL scripts. What database are you using?

Regards

**Comment by glerler** [comment]
It is SQL and it was an existing site db.

I did get the problem resolved.

The db shows in SQL but  something got hosed in the data when I migrated the db.

I deleted and restored again and it fired up.

The issue had nothing to do with  Piranha.

Thx for the follow-up

Glenn


________________________________
