### ISSUE TITLE
Open redirect issues

### ISSUE THREAD

**Issue by alexxn** [PiranhaCMS/Piranha#545]
Hey,
There are numerous Open Redirect issues in Piranha.
Core\Piranha\Web\AuthController.cs

Controller action Logout() is using unvalidated parameter directly from Request object
`string returl = Request["returnurl"];`

Controller action Login() uses
`Request["returnurl"];`
`Request["failureurl"];
`
Action NewPassword() consumes 2 unvalidated URLs from user input
`Request["returnurl"];`
`Request["failureurl"];`

To mitigate this issue Piranha should validate that redirect URL belongs to a whitelisted domain i.e. to the same domain where application is running.

You can read more about Open Redirects here:
https://www.owasp.org/index.php/Unvalidated_Redirects_and_Forwards_Cheat_Sheet

**Comment by tidyui** [comment]
Sounds good! Feel free to make a fork and send me a pull request and I'll include it in the next service release! Otherwise I will take care of it as soon as I get the time.

Best regards

Håkan
