### ISSUE TITLE
Override the JQuery Version

### ISSUE THREAD

**Issue by gyretech** [PiranhaCMS/Piranha#549]
Is it possible to override or upgrade the JQuery Version in the Manager?

**Comment by tidyui** [comment]
Unfortunately not atm!

/Regards

**Comment by gyretech** [comment]
So what are my options for slightly higher version on jquery?

**Comment by tidyui** [comment]
Either we upgrade the manager OR you can use another version of jquery in parallel if you prefix it! However this doesn't work if you want to use other third party that uses the default namespace!
