### ISSUE TITLE
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

### ISSUE THREAD

**Issue by leviathan898** [PiranhaCMS/Piranha#550]
Hi,

I've recently been trying out Piranha CMS to use in a project and have created n MVC project uisng it from scratch and developing with it successfully.

1) I want to use it for an existing MVC project with Entity Framework, but after following the steps in Getting Started, I come across the above error when I try to run and debug the program to install the website (database and admin). I've combed through my bin folder, as well as my references and Web.config (even comparing Web.configs between the test Piranha project, my project pre-Piranha and my post-Piranha project) and haven't come across anything that resolves this issue.

2) I've tried setting disableComposition and/or disableCatalogSearch to true, which allows my project to debug and allow me to continue to admin setup and login, but at that point the page just keeps redirecting me to the login page. I've set authentication to what Piranha inserts into the Web.config, but to no avail. I have read briefly that using Owin could be an issue, but haven't read anything specific about Owin and this login issue.

Any help would be much appreciated, I've spent a day and a half trying to figure this out! I'm using MVC 5.2.3, PiranhaCore 2.2.7.2, Piranha.Mvc 2.2.6 and PiranhaMvc 2.2.6.1. Below is the error I get for problem 1).

`[ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.]
   System.Reflection.RuntimeModule.GetTypes(RuntimeModule module) +0
   System.Reflection.RuntimeModule.GetTypes() +9
   System.Reflection.Assembly.GetTypes() +61
   System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog() +176
   System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition) +11
   System.ComponentModel.Composition.Hosting.<>c__DisplayClass34_0.<GetExports>b__0(ComposablePartCatalog catalog) +19
   System.Linq.<SelectManyIterator>d__16`2.MoveNext() +215
   System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) +225
   System.ComponentModel.Composition.Hosting.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) +18
   System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) +31
   System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) +28
   System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) +58
   System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) +31
   System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) +336
   System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) +31
   System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition) +157
   System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports) +31
   System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition) +35
   System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition) +43
   System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition) +164
   System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part) +556
   System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports) +122
   System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part) +103
   System.ComponentModel.Composition.Hosting.<>c__DisplayClass19_0.<Compose>b__0() +26
   System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action) +28
   System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch) +783
   System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch) +35
   System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts) +225
   Piranha.Application.Initialize() +229
   Piranha.Application..ctor() +88
   Piranha.Application..cctor() +30

[TypeInitializationException: The type initializer for 'Piranha.Application' threw an exception.]
   Piranha.WebPages.WebPiranha.BeginRequest(HttpContext context) +1833
   Piranha.Web.<>c.<Init>b__2_0(Object sender, EventArgs e) +50
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   Piranha.WebPages.WebPiranha.BeginRequest(HttpContext context) +1833
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69
   Piranha.Web.<>c.<Init>b__2_0(Object sender, EventArgs e) +50
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +141
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69`

**Comment by leviathan898** [comment]
So I literally just found this [](http://stackoverflow.com/questions/33778238/piranha-cms-login-issue) so problem 2) is sort of solved I guess. However, as I have set disableComposition/disableCatalogSearch = true, will these have repercussions to using Piranha, using it with my site, or the development side of my site _sans_ Piranha?

**Comment by tidyui** [comment]
Hi there!

The error message from your first post is usually related to a dll that references a dll that is **not** included in you bin-folder. This is just how MEF reacts when trying to load the assemblies.

Now to the the config options you mention, because they work in different ways.

### DisableCatalogSearch
This tells the framework to **only** scan the Piranha dll's for extensions. This means that only the extensions (regions) included in the core framework will be available, not custom ones you add in your project.

### DisableComposition
This completely disables MEF composition causing **NO** extensions or regions to be added. This can be useful when your project has A LOT of references and DLL's and you want to optimize the startup time of the application. In order for the application to work you have to add the extensions/regions you want to use manually in your startup code like:

    Piranha.Application.Compose(c => {
        c.Framework = new Piranha.Mvc.ClientFramework();
        c.RouteHandler = new Piranha.Mvc.RouteHandler();
    });
    Piranha.Extend.ExtensionManager.Compose(c => {
        c.Extensions.Add(new Piranha.Extend.Regions.AttachmentRegion());
        c.Extensions.Add(new Piranha.Extend.Regions.HtmlRegion());
        c.Extensions.Add(new Piranha.Extend.Regions.ImageRegion());
        c.Extensions.Add(new Piranha.Extend.Regions.PostModelRegion());
        c.Extensions.Add(new Piranha.Extend.Regions.PostRegion());
        c.Extensions.Add(new Piranha.Extend.Regions.TextRegion());
    });

This will add the basic extensions and set the application up for MVC.

Regards

**Comment by leviathan898** [comment]
Thanks for the reply!

So basically, it could be a reference I have in the project that doesn't have a corresponding dll, or it could be that some reference with a dll in the bin references another one that isn't there? And that means in the latter case, it would be trying to find a needle in a haystack?

I'll retry DisableComposition again with what you've supplied above, but the explanation of DisableCatalogSearch doesn't quite match up to what's occurring everytime I try adding or accessing a page/post. As I'm trying to integrating Piranha to an existing project for the first time, I wouldn't have any custom extensions/regions, so I don't know why it would break and have a NullException.

Update: I've cloned my project again to attempt one final try to get Piranha working with my existing MVC project, butnow I get **Failed to add reference. The package 'PiranhaCMS.Core' tried to add a framework reference to 'System.Linq' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.**. This occurred to me before and then it magically disappeared somehow (and I could install Piranha, leading to the above errors). I know someone found a resolution here [#535](https://github.com/PiranhaCMS/Piranha/issues/535), but I've just tried removing the reference to  System.Net.Http and installing Piranha to no avail.

**Comment by tidyui** [comment]
Do you have the same version of System.Linq installed on your machine, or do you only have the latest version of .NET installed in you development environment?

**Comment by tidyui** [comment]
The simplest way to pinpoint the incompability with your environment would propably just be to clone the repo and take a look at the references.
