### ISSUE TITLE
Media is Write Protected in AWS Using putobject?

### ISSUE THREAD

**Issue by eswarg02** [PiranhaCMS/Piranha#554]
Hi Folks,
Media is write protected Error while uploading 6499 PDF File to Nuance server ? Is that any limitation? Thanks in advance..

**Comment by tidyui** [comment]
Hi there! As I've never actually tried AWS myself (as we only use Azure where I work) I'm not familiar with how they setup file system permissions on their servers. Media files are uploaded to:

    ~/App_Data/Content/

and the framework also needs write permissions to the folder

    ~/App_Data/Cache/

as scaled & cropped versions of images are stored in that folder. Please let me know what conclusion you come to as it would be good to add an information section about how to deploy to different cloud providers.

Best regards!

Håkan
