### ISSUE TITLE
Unable to Install Piranha CMS in ASP.Net MVC Application: Failed to add reference to 'System.Linq'

### ISSUE THREAD

**Issue by TenTonsOfHat** [PiranhaCMS/Piranha#555]
Piranha CMS looks like it would be a great fit for our existing site. I wanted to test out the functionality so I followed the guide found here: 

https://piranhacms.org/docs/introduction/getting-started 

When I try to install it into my VS 2015 project with NuGet (using Install-Package PiranhaCMS.Mvc) the process works through several packages, and gets to the point where I see these lines: 

Adding package 'PiranhaCMS.Core.2.2.6' to folder 'C:\<MyPath>\SolutionDirectory\packages'
Added package 'PiranhaCMS.Core.2.2.6' to folder 'C:\<MyPath>\SolutionDirectory\packages'
Install failed. Rolling back... 

After it finishes removing packages I see this: 
**Failed to add reference to 'System.Linq'. Please make sure that it is in the Global Assembly Cache.**

Whats strange is that my project is built against .net 4.5.2. and as far as I am aware system.linq is now just a part of System.Core.dll so I wouldn't expect it to be on its own in the GAC. 

Any ideas on how I might resolve this issue?

**Comment by tidyui** [comment]
Hmmm.. The current version builds against the .NET 4.5 framework for backwards compatibility. If you can install 4.5.2 as a standalone installation my guess is that you don't have the GAC assemblies for System.Linq for 4.5?

Regards
