### ISSUE TITLE
'Piranha.Models.PostModel' does not contain a definition for 'Regions'

### ISSUE THREAD

**Issue by CentricStraaten** [PiranhaCMS/Piranha#556]
I entered a post via the manager. When call the URL i get the exception 'Piranha.Models.PostModel' does not contain a definition for 'Regions'. 

It breaks on  @RenderSection("head", required: false) ? An example http://weerbaar.com/de-weg-van-de-krijger.

How do is solve this problem?

**Comment by tidyui** [comment]
Post models don't have regions, only Page models have. You need to check in your shared views if the current model is a Page or a Post.

Regards

Håkan

**Comment by CentricStraaten** [comment]
If have done like you proposed. The exception still occurs but now on a css bundle?

![image](https://user-images.githubusercontent.com/17175831/30450310-9df562c8-9991-11e7-98e4-e3e2d41686b9.png)
