### ISSUE TITLE
Read-Only access

### ISSUE THREAD

**Issue by humanbeinc** [PiranhaCMS/Piranha#561]
I couldn't figure out how to create a read-only user-group. The system-default permissions for these settings seem to be missing. Is it generally possible to achieve that without changig code?

Improvement idea:
A good default setup for CMS groups would be:
- Sysadmin
- Admin
- Publisher
- Editor
- Viewer

and permissions:
- CRUD for each type
- Publish/Unpublish for each type

**Comment by tidyui** [comment]
Unfortunately the manager permissions are not setup this way, you can only enable/disable on entity level, not set allowed action.
