### ISSUE TITLE
Image selector (for ImageRegion) doesn't obey "managerUrl" parameter

### ISSUE THREAD

**Issue by humanbeinc** [PiranhaCMS/Piranha#562]
Always links to: /manager/content/popup?tinymce=false&filter=none

**Comment by tidyui** [comment]
I'm guessing this line is the problem.  https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Content/Js/jquery.media.dialog.js#L27

Unfortunately this probably also means that the media dialog doesn't work when used in the HTML editor either.
