### ISSUE TITLE
Question: Upgrading to .net core version

### ISSUE THREAD

**Issue by Eonasdan** [PiranhaCMS/Piranha#565]
I currently have a blog site on v2.2.5.0. I want to upgrade to the new .net core version. Will I lose my permalinks doing this? Do I need to create a new database? I'm not worried about changes to the front end as I kind of what to redo that anyway and get a fresh coat of paint.

**Comment by tidyui** [comment]
Hi there! The .net core version is completely rewritten and have a completely different database structure than the `2.x` version. I have not created any migration scripts as it's very hard to do any generic scripts as the new version depends on the structure of the Page Types you import.

Regarding your permalinks **posts** are handled slightly different in the .net core version, as post permalinks are made up of:

    /<blogSlug>/<postSlug>

So putting the post `my-first-post` under the blog `news` would generate the permalink `/news/my-first-post`.

**HOWEVER** the .net core includes an **Alias** module out of the box which you can use to set up redirects from your old permalinks to your new ones so you don't loose your indexed links in the search  engines.

Regards
