### ISSUE TITLE
Adding content programatically - options?

### ISSUE THREAD

**Issue by benyoungnz** [PiranhaCMS/Piranha#567]
I've looked for posts on API/programmatically adding content some of which are quite old and others were simply commented on as "this is a silly way to do it"

I have the need to push content into a CMS for a a custom type, the engine that lives here could live on a script that lives within the CMS application itself if required such as via a hangfire schedule - what is the recommended approach here/is there one?

**Comment by tidyui** [comment]
I'm not sure I follow your question exactly. Do you want to add content programatically into an existing Piranha CMS application or are you investigating for a solution that supports this use case?

If you're looking for a solution and aren't adding functionality to an existing Piranha 2.x installation I would recommend investigating the new version of Piranha which has much better support for this. You can find the repo here:

https://github.com/PiranhaCMS/piranha.core

You can see an example of seeding/adding content with code in the example web in the repository here:

https://github.com/PiranhaCMS/piranha.core/blob/master/examples/CoreWeb/Startup.cs#L111

If you an existing application based on the old 2.x version of Piranha get back to me here and lets see what we can do!

Regards

**Comment by benyoungnz** [comment]
@tidyui Looking for a solution that fits this use case with priority on Piranha. That is perfect thanks for the heads up on that i was starting to deconstruct the manager pages to get around it but that is a lot nicer.

I'll put something together and report back!

Thanks
