### ISSUE TITLE
Quickest way to change the default area

### ISSUE THREAD

**Issue by amh2013** [PiranhaCMS/Piranha#569]
For for security and other reasons, whats the quickest way to change /manager url to something more custom?

Might even be a good feature to lock down the admin url by IP so no one else can get to that page.

**Comment by tidyui** [comment]
The `/manager` route is not configurable atm, but this feature was implemented in the legacy version (`2.x`) so there's probably some code there we could migrate.

As for locking certain paths to IP this must be achievable with web site configuration.

Also, as long as you implement a distributed cache provider you could deploy the manager interface on a completely different machine than the public website if you want.

**Comment by tidyui** [comment]
Oh sorry.. I see this issue **IS** actually added in the old version of Piranha CMS (`2.x`). In this version there is a setting available in `web.config` for changing the manager route :) I'm so used getting all of the questions in the new repo.

**Comment by amh2013** [comment]
@tidyui tdyui appreciate you response.  First of all on your second point its not in the web.config .net core version as you know web.config is hardly used. 

Can you elaborate slightly on the below.

> Also, as long as you implement a distributed cache provider you could deploy the manager interface on a completely different machine than the public website if you want.

**Comment by tidyui** [comment]
Hi! It’s hard to answer correctly if you open the issue in the wrong repo. This repo is for the old .NET 4.5 version of Piranha. If you’re question is about the .NET Core version, please close this issue and open a new one in:

https://github.com/PiranhaCMS/piranha.core

Regards
