### ISSUE TITLE
Using MySql database

### ISSUE THREAD

**Issue by Luciano74** [PiranhaCMS/Piranha#572]
Hi, I'm having trouble using parahna with MySql. I have tried the example at the following repo: https://github.com/aatmmr/piranha-core-mysql 
It's working fine, but only with the parahna 4.31 release. 

I wan't to use the 5.3.1 release. How can this be done?

**Comment by tidyui** [comment]
Hi there! This is the legacy version of Piranha CMS (2.x), I'll close your issue and let you open a new one here:

https://github.com/PiranhaCMS/piranha.core/issues

Regards
