### ISSUE TITLE
How to get Page/Post (content only) in passive mode?

### ISSUE THREAD

**Issue by beany-vu** [PiranhaCMS/Piranha#575]
Hi,

I'm the newbie to the .NET world and I'm trying to bring the PiranhaCMS into an existing MVC website (.NET). I can install the CMS by this command:
`Install-Package PiranhaCMS.Mvc`

1. I have a post created for now. I want to show the post content into a View. So I'm use these line of code in my controller (extends from BaseController):
```
 public ActionResult Index()
        {
	var page = Piranha.Models.Page.GetByPermalink("en/start");
	var model = Piranha.Models.PageModel.Get(page);
        ...
	return View(model);
        }

```

2. Also added this line code in the beginning of the view files:
`@model Piranha.Models.PageModel`

3. And this code in the position I want to get the content (I dont know about the data property so I chose Page for now):
`@Model.Page`

I can see the result I got when running the project is this string 'Piranha.Models.Page'.

Anyone has experience the similar situation like me? Please give me some idea, keyword or sample code... so that I can get the issue.

Thanks!

**Comment by tidyui** [comment]
Hi again. The output should be `Piranha.Models.Page` (just like you're getting) as you're printing a complex object of that type without a `DisplayTemplate` available for it.

I think the easiest way for you to get started would be to actually create an empty project from the full project template and take a look at how the example pages included are rendered in razor. You can create a new blank MVC application by installing the package `PiranhaCmsMvc` into an empty application. 

http://legacy.piranhacms.org/docs/introduction/getting-started

Best regards

**Comment by beany-vu** [comment]
@tidyui ,
Thank you for your sharing!
I can show the page on frontend by myself finally.
Have a good day, my hero!!!
