### ISSUE TITLE
Suggestion - prefix db tables

### ISSUE THREAD

**Issue by stonetwig** [PiranhaCMS/Piranha#576]
Hey,

Right now you cannot have multiple installations on the same DB. A nice feature would be to have prefixes on the tables as a choice. Many hosting alternatives maybe only give you one table which makes it unnecessary expensive or hard to host multiple installations on those.

Thanks,
Markus

**Comment by tidyui** [comment]
Hi there @stonetwig Is this question intended for this repo or for the .Net Core version which is located in this repo: https://github.com/PiranhaCMS/piranha.core
