### ISSUE TITLE
Suggestion - preview changes before saving a published page

### ISSUE THREAD

**Issue by morkonom** [PiranhaCMS/Piranha#577]
A preview button that would save a temporary page for viewing would be a nice feature. Previewing changes to already published pages isn't very meaningful if you have to save the page first.

**Comment by tidyui** [comment]
Hi there! We are not actively developing this version of Piranha CMS as it is the old legacy version for .NET 4.x. Did you mean to add it to the current version for .NET Core? https://github.com/PiranhaCMS/piranha.core

**Comment by morkonom** [comment]
Oops, I sure did. I will move it! Thanks.
