### ISSUE TITLE
TinyMCE fails to load piranhaimage

### ISSUE THREAD

**Issue by ChristopheCuddlup** [PiranhaCMS/Piranha#578]
Hi,
I upgraded my ASP.Net core project from Piranha version 6.0.1 to 7.0.
I have an error in the Browser console when running the manager:
Failed to initialize plugin: piranhaimage Error: editor.addButton has been removed in tinymce 5x, use editor.ui.registry.addButton or editor.ui.registry.addToggleButton or editor.ui.registry.addSplitButton instead
    at eN.addButton (tinymce.min.js:9)
    at new <anonymous> (plugin.min.js:106)
    at Hw (tinymce.min.js:9)
    at Array.<anonymous> (tinymce.min.js:9)
    at Object.jt [as each] (tinymce.min.js:9)
    at Iw (tinymce.min.js:9)
    at eN.<anonymous> (tinymce.min.js:9)
    at Array.<anonymous> (tinymce.min.js:9)
    at jt (tinymce.min.js:9)
    at o (tinymce.min.js:9)

Looking at piranhaimage plugin source code (here: https://github.com/PiranhaCMS/Piranha/blob/master/Core/Piranha/Areas/Manager/Content/Js/Ext/tiny_mce/plugins/piranhaimage/plugin.min.js ), I can see the last but one function editor.addButton() is present.
I believe this line should be changed to one of the suggested methods in the error text.
Is there something I can do in the meantime?

Thanks and regards
Christophe

**Comment by tidyui** [comment]
Tiny 5.0 is completely different from 4.x. In conjunction with the fact that it uses a rather aggressive cache strategy you need to clear your browser history if you toggle between 6.x and 7.0.

Regards

**Comment by tidyui** [comment]
And this is actually the wrong repo, this is the repo for the old legacy version of Piranha (2.x) :)

**Comment by ChristopheCuddlup** [comment]
Thank you, I'll try this!

Le lun. 26 août 2019 à 23:42, Håkan Edling <notifications@github.com> a
écrit :
